namespace AlvorKit.Script.Bindgen;

/// <summary>Shared formatting context for generated OpenGL source artifacts.</summary>
/// <param name="Config">Bindgen configuration that controls output names and paths.</param>
/// <param name="RegistryTag">OpenGL registry source tag or commit used in attribution.</param>
/// <param name="DocTag">OpenGL refpage source tag or commit used in attribution.</param>
internal sealed record GlCodeEmissionContext(
    BindgenConfig Config,
    string RegistryTag,
    string DocTag)
{
    /// <summary>Human-readable source description embedded in generated comments.</summary>
    public string Origin =>
        $"the OpenGL registry at {RegistryTag[..Math.Min(12, RegistryTag.Length)]} ({Config.GlApi} {Config.GlVersion} {Config.GlProfile})";

    /// <summary>XML auto-generated banner for project files.</summary>
    public string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {Origin}. -->";

    /// <summary>C# auto-generated header shared by generated source files.</summary>
    public StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine("// <auto-generated/>")
        .AppendLine("#nullable enable")
        .AppendLine();

    /// <summary>Formats availability text for docs, preserving extension names verbatim.</summary>
    public static string AvailabilityText(GlAvailability availability)
    {
        var desktop = char.IsAsciiDigit(availability.Gl[0]) ? $"GL {availability.Gl}" : availability.Gl;
        return availability.GlEs is null ? desktop : $"{desktop}, GL ES {availability.GlEs}";
    }
}
