namespace AlvorKit.Script.Bindgen.CHeaders.Test;

[TestClass]
public sealed class BindingCodeEmitterTest
{
    [TestMethod]
    public void EmitNativeImports_UsesExplicitCdeclCallingConvention()
    {
        using var workspace = TempWorkspace.Create();
        var config = CHeaderTestConfig.Create();
        var model = new BindingModel(
            Enums: [],
            Structs: [],
            Handles: [],
            Delegates: [],
            Functions:
            [
                new(
                    NativeName: "test_add",
                    ManagedName: "Add",
                    ReturnType: "int",
                    ReturnInteropType: "int",
                    Parameters:
                    [
                        new("left", "int", "int", "", HasStringConvenience: false),
                        new("right", "int", "int", "", HasStringConvenience: false)
                    ],
                    Documentation: null)
            ],
            Constants: [],
            SkippedFunctions: [],
            SizeofTypes: []);

        new BindingCodeEmitter(config, "1.0.0").Emit(model, workspace.Root, "1.0.0", "1.0.0");

        var nativeSource = File.ReadAllText(Path.Combine(workspace.Root, config.BackendProject, "TestNative.cs"));
        StringAssert.Contains(nativeSource, "[LibraryImport(Lib, EntryPoint = \"test_add\")]");
        StringAssert.Contains(nativeSource, "[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
    }

    /// <summary>Pointer-shaped public bindings emit unsafe members and pointer fields.</summary>
    [TestMethod]
    public void EmitPointerTypes_AddsUnsafeModifiers()
    {
        using var workspace = TempWorkspace.Create();
        var config = CHeaderTestConfig.Create();
        var model = new BindingModel(
            Enums: [],
            Structs: [new("test_face_rec", "TestFaceRec", false, 16, [new("Next", "TestFaceRec*", 0, null)], [], null)],
            Handles: [],
            Delegates: [],
            Functions:
            [
                new(
                    NativeName: "test_current",
                    ManagedName: "Current",
                    ReturnType: "TestFaceRec*",
                    ReturnInteropType: "TestFaceRec*",
                    Parameters: [new("face", "TestFaceRec*", "TestFaceRec*", "", HasStringConvenience: false)],
                    Documentation: null)
            ],
            Constants: [],
            SkippedFunctions: [],
            SizeofTypes: []);

        new BindingCodeEmitter(config, "1.0.0").Emit(model, workspace.Root, "1.0.0", "1.0.0");

        StringAssert.Contains(File.ReadAllText(Path.Combine(workspace.Root, config.ApiProject, "TestFaceRec.cs")), "public unsafe struct TestFaceRec");
        StringAssert.Contains(File.ReadAllText(Path.Combine(workspace.Root, config.ApiProject, "Test.cs")), "public unsafe virtual TestFaceRec* Current");
        StringAssert.Contains(
            File.ReadAllText(Path.Combine(workspace.Root, config.BackendProject, "TestNative.cs")),
            "public static unsafe partial TestFaceRec* Current");
    }

    [TestMethod]
    public void EmitBackendProject_AlwaysReferencesNativePackage()
    {
        using var workspace = TempWorkspace.Create();
        var config = CHeaderTestConfig.Create();
        var model = new BindingModel([], [], [], [], [], [], [], []);

        new BindingCodeEmitter(config, "1.0.0").Emit(model, workspace.Root, "2.0.0", "1.0.0");

        var backendProject = File.ReadAllText(Path.Combine(workspace.Root, config.BackendProject, "Fixture.Backend.csproj"));
        StringAssert.Contains(backendProject, "<Version>2.0.0</Version>");
        StringAssert.Contains(backendProject, "<PackageReference Include=\"AlvorKit.Bindgen.Fixture.Native\" Version=\"1.0.0\" />");
        Assert.IsFalse(backendProject.Contains("AlvorKitSkipNativePackageReference", StringComparison.Ordinal));
    }

    /// <summary>Alternate output roots receive generated projects directly under the requested snapshot directory.</summary>
    [TestMethod]
    public void Emit_CanWriteToAlternateOutputRoot()
    {
        using var workspace = TempWorkspace.Create();
        var config = CHeaderTestConfig.Create();
        var model = new BindingModel([], [], [], [], [], [], [], []);
        var outputRoot = Path.Combine(workspace.Root, "out", "bindgen-review", "after");

        new BindingCodeEmitter(config, "1.0.0").Emit(model, workspace.Root, outputRoot, "1.0.0", "1.0.0");

        Assert.IsTrue(File.Exists(Path.Combine(outputRoot, "Directory.Build.props")));
        Assert.IsTrue(File.Exists(Path.Combine(outputRoot, "Fixture", "Fixture.csproj")));
        Assert.IsTrue(File.Exists(Path.Combine(outputRoot, "Fixture.Backend", "Fixture.Backend.csproj")));
        Assert.IsFalse(Directory.Exists(Path.Combine(workspace.Root, config.ApiProject)));
    }

    /// <summary>Sizeof shims emit an autogenerated C source with one export per requested native type.</summary>
    [TestMethod]
    public void EmitSizeofShim_WritesConfiguredSizeExports()
    {
        var config = CHeaderTestConfig.Create();
        config.ShimExport = "ALVORKIT_EXPORT";
        var emitter = new BindingCodeEmitter(config, "1.0.0");
        var empty = emitter.EmitSizeofShim(new BindingModel([], [], [], [], [], [], [], []));

        StringAssert.Contains(empty, "// <auto-generated/>");
        Assert.IsFalse(empty.Contains("alvorkit_sizeof_", StringComparison.Ordinal));

        var shim = emitter.EmitSizeofShim(new BindingModel([], [], [], [], [], [], [], ["test_context", "test_state"]));

        StringAssert.Contains(shim, "// Generated by AlvorKit.Script.Bindgen from fixture 1.0.0 (fixture.h).");
        StringAssert.Contains(shim, "ALVORKIT_EXPORT size_t alvorkit_sizeof_test_context(void) { return sizeof(test_context); }");
        StringAssert.Contains(shim, "ALVORKIT_EXPORT size_t alvorkit_sizeof_test_state(void) { return sizeof(test_state); }");
    }

    [TestMethod]
    public void EmitStringReturn_SpanOverloadHandlesNullNativePointer()
    {
        using var workspace = TempWorkspace.Create();
        var config = CHeaderTestConfig.Create();
        var model = new BindingModel(
            Enums: [],
            Structs: [],
            Handles: [],
            Delegates: [],
            Functions:
            [
                new(
                    NativeName: "test_description",
                    ManagedName: "Description",
                    ReturnType: "nint",
                    ReturnInteropType: "nint",
                    Parameters: [],
                    Documentation: null,
                    ReturnsCString: true)
            ],
            Constants: [],
            SkippedFunctions: [],
            SizeofTypes: []);

        new BindingCodeEmitter(config, "1.0.0").Emit(model, workspace.Root, "1.0.0", "1.0.0");

        var overloads = File.ReadAllText(Path.Combine(workspace.Root, config.ApiProject, "TestOverloads.cs"));
        StringAssert.Contains(overloads, "var pointer = Description();");
        StringAssert.Contains(overloads, "if (pointer == 0) { result = default; return; }");
        StringAssert.Contains(overloads, "MemoryMarshal.CreateReadOnlySpanFromNullTerminated((byte*)pointer)");
    }

}
