<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.ECS.Demo.Bench" />
        <InternalsVisibleTo Include="AlvorKit.ECS.Test" />
        <Using Include="AlvorKit.Hashing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.Hashing\AlvorKit.Hashing.csproj" />
    </ItemGroup>

</Project>
