<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>CoreCLR ReJIT backend and exact managed trampolines for AlvorKit interception.</Description>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.Interception\AlvorKit.Interception.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Interception.CoreClr.Advanced" />
        <Using Include="System.Reflection.Emit" />
        <InternalsVisibleTo Include="AlvorKit.Interception.Test" />
    </ItemGroup>

    <ItemGroup Condition="!Exists('$(BindingsRoot)\AlvorKit.Interception.Profiler.Backend\AlvorKit.Interception.Profiler.Backend.csproj')">
        <PackageReference
            Include="AlvorKit.Interception.Profiler.Backend"
            Version="$(InterceptionProfilerBindVer)" />
    </ItemGroup>

    <ItemGroup Condition="Exists('$(BindingsRoot)\AlvorKit.Interception.Profiler.Backend\AlvorKit.Interception.Profiler.Backend.csproj')">
        <ProjectReference
            Include="$(BindingsRoot)\AlvorKit.Interception.Profiler.Backend\AlvorKit.Interception.Profiler.Backend.csproj" />
    </ItemGroup>

</Project>
