namespace AlvorKit;

/// <summary>Reconciles one generated repository solution without consulting any previous solution membership.</summary>
internal static class SolutionGenerator
{
    /// <summary>Evaluates the graph, checks freshness, and optionally publishes changed output atomically.</summary>
    public static bool Generate(string root, bool check, SolutionWatchInputs? inputs)
    {
        try { return Publish(Prepare(root, inputs), check); }
        catch
        {
            if (!check)
                Invalidate(root);

            throw;
        }
    }

    /// <summary>Evaluates and serializes without writing, allowing a watcher to reject a changed checkout.</summary>
    internal static SolutionGeneration Prepare(string root, SolutionWatchInputs? inputs)
    {
        var fullRoot = Path.GetFullPath(root);

        foreach (var path in Directory.EnumerateFiles(fullRoot, "*.slnx"))
        {
            if (!IsGenerated(path))
                throw new InvalidOperationException($"Remove the authored solution before generating this repository: {path}");
        }

        var projects = SolutionGraph.Read(fullRoot, inputs);
        return new(fullRoot, SolutionDocument.Format(fullRoot, projects), projects.Count);
    }

    /// <summary>Publishes only a complete document, replacing existing output atomically when it changes.</summary>
    internal static bool Publish(SolutionGeneration generation, bool check)
    {
        var (fullRoot, content, count) = generation;
        var output = RepositoryProjects.SolutionPath(fullRoot);
        var changed = !File.Exists(output) || File.ReadAllText(output) != content;

        if (changed && !check)
            Write(output, content);

        if (changed || check)
            Console.WriteLine($"{(changed ? check ? "Stale" : "Wrote" : "Current")} {output} ({count} projects).");

        var obsolete = Directory.EnumerateFiles(fullRoot, "*.slnx")
            .Where(path => !SolutionPaths.Comparer.Equals(path, output) && IsGenerated(path)).ToArray();

        foreach (var path in obsolete)
        {
            if (check)
                Console.WriteLine($"Obsolete generated solution: {path}");
            else File.Delete(path);
        }

        return !check || (!changed && obsolete.Length == 0);
    }

    /// <summary>Removes our previous output if the project graph is invalid; never deletes authored solutions.</summary>
    public static void Invalidate(string root)
    {
        try
        {
            foreach (var path in Directory.EnumerateFiles(root, "*.slnx").Where(IsGenerated))
                File.Delete(path);
        }
        catch (DirectoryNotFoundException) when (!Directory.Exists(root)) { }
    }

    /// <summary>Keeps empty repositories discoverable until their last generated solution is invalidated.</summary>
    internal static bool HasGeneratedSolution(string root) => Directory.EnumerateFiles(root, "*.slnx").Any(IsGenerated);

    /// <summary>Identifies files owned by this generator, including a previous checkout name.</summary>
    private static bool IsGenerated(string path)
    {
        try { return File.ReadAllText(path).Contains("Generated by AlvorKit.Script.Solution.", StringComparison.Ordinal); }
        catch (FileNotFoundException) { return false; }
        catch (DirectoryNotFoundException) { return false; }
    }

    /// <summary>Only replaces the destination after a complete document has been serialized successfully.</summary>
    private static void Write(string output, string content)
    {
        var temporary = output + "." + Guid.NewGuid().ToString("N") + ".tmp";

        try
        {
            File.WriteAllText(temporary, content, new UTF8Encoding(false));
            File.Move(temporary, output, true);
        }
        finally
        {
            if (File.Exists(temporary))
                File.Delete(temporary);
        }
    }
}
