namespace AlvorKit;

/// <summary>Serializes a complete evaluated graph as a deterministic, buildable SLNX document.</summary>
internal static class SolutionDocument
{
    /// <summary>Preserves explicit configuration membership and derives presentation from directory structure.</summary>
    public static string Format(string root, IReadOnlyList<SolutionProject> projects)
    {
        var solution = new XElement("Solution", new XComment(
            " Generated by AlvorKit.Script.Solution. Edit project files, then regenerate. Do not commit this file. "));
        var folders = new Dictionary<string, XElement>(StringComparer.Ordinal);

        foreach (var project in projects.OrderBy(project => SolutionPaths.Relative(root, project.Path), StringComparer.Ordinal))
        {
            var element = new XElement("Project", new XAttribute("Path", SolutionPaths.Relative(root, project.Path)));

            if (project.Startup)
                element.Add(new XAttribute("DefaultStartup", "true"));

            foreach (var configuration in SolutionGraph.Configurations)
            {
                if (!project.Configurations.Contains(configuration))
                    element.Add(new XElement("Build", new XAttribute("Solution", configuration + "|*"),
                        new XAttribute("Project", "false")));
            }

            var folder = Folder(root, project.Path);

            if (folder.Length == 0)
            {
                solution.Add(element);
                continue;
            }

            var segments = folder.Split('/');

            for (var length = 1; length <= segments.Length; length++)
            {
                var name = "/" + string.Join('/', segments.Take(length)) + "/";

                if (!folders.ContainsKey(name))
                {
                    var container = new XElement("Folder", new XAttribute("Name", name));
                    folders.Add(name, container);
                    solution.Add(container);
                }
            }

            folders["/" + folder + "/"].Add(element);
        }

        return new XDocument(solution).ToString().Replace("\r\n", "\n") + "\n";
    }

    /// <summary>Groups local projects by source area and sibling engine dependencies under Engine.</summary>
    private static string Folder(string root, string project)
    {
        if (SolutionPaths.IsWithin(root, project))
            return ProjectDirectory(SolutionPaths.Relative(root, project));

        var parent = Directory.GetParent(root)?.FullName ?? root;
        var engine = Path.Combine(parent, "AlvorKit");

        if (SolutionPaths.IsWithin(engine, project))
            return ("Engine/" + ProjectDirectory(SolutionPaths.Relative(engine, project))).TrimEnd('/');

        return "Dependencies";
    }

    /// <summary>Flattens the source area, omits matching project leaves, and capitalizes the remaining folder labels.</summary>
    private static string ProjectDirectory(string relative)
    {
        var directory = Path.GetDirectoryName(relative) ?? "";

        if (Path.GetFileName(directory) == Path.GetFileNameWithoutExtension(relative))
            directory = Path.GetDirectoryName(directory) ?? "";

        var segments = directory.Replace('\\', '/').Split('/', StringSplitOptions.RemoveEmptyEntries);

        if (segments.Length > 0 && segments[0].Equals("src", StringComparison.OrdinalIgnoreCase))
            segments = segments[1..];

        return string.Join('/', segments.Select(segment => char.ToUpperInvariant(segment[0]) + segment[1..]));
    }
}
