namespace AlvorKit;

/// <summary>Owns generated solution files and publishes complete documents atomically.</summary>
internal static class SolutionOutput
{
    /// <summary>Recognizes only the solution generator's output, including previous checkout names.</summary>
    internal static bool IsGenerated(string path)
    {
        try { return File.ReadAllText(path).Contains("Generated by AlvorKit.Script.Solution.", StringComparison.Ordinal); }
        catch (FileNotFoundException) { return false; }
        catch (DirectoryNotFoundException) { return false; }
    }

    /// <summary>Rejects authored output instead of replacing a user's solution.</summary>
    internal static void Validate(string path)
    {
        if (File.Exists(path) && !IsGenerated(path))
            throw new InvalidOperationException($"Remove the authored solution before generating: {path}");
    }

    /// <summary>Checks freshness without writes, or replaces output only when its complete contents changed.</summary>
    internal static bool Publish(string output, string content, int count, bool check)
    {
        Validate(output);
        var changed = !File.Exists(output) || File.ReadAllText(output) != content;

        if (changed && !check)
            Write(output, content);

        if (changed || check)
            Console.WriteLine($"{(changed ? check ? "Stale" : "Wrote" : "Current")} {output} ({count} projects).");

        return !check || !changed;
    }

    /// <summary>Removes stale generated output while preserving authored files.</summary>
    internal static void Invalidate(string path)
    {
        if (IsGenerated(path))
            File.Delete(path);
    }

    /// <summary>Only replaces the destination after a complete document has been serialized successfully.</summary>
    private static void Write(string output, string content)
    {
        var temporary = output + "." + Guid.NewGuid().ToString("N") + ".tmp";

        try
        {
            File.WriteAllText(temporary, content, new UTF8Encoding(false));
            File.Move(temporary, output, true);
        }
        finally
        {
            if (File.Exists(temporary))
                File.Delete(temporary);
        }
    }
}
