using DevSolutionGenerator = AlvorKit.Script.DevSolution.DevSolutionGenerator;
using DevSolutionOptions = AlvorKit.Script.DevSolution.DevSolutionOptions;

namespace AlvorKit.Script.ZoneSolution;

/// <summary>Generates a deterministic .slnx that groups sibling repositories by solution folder.</summary>
internal sealed class ZoneSolutionGenerator
{
    private const string EngineRepositoryName = "AlvorKit";
    private const string GeneratedComment =
        " Generated by AlvorKit.Script.ZoneSolution. Do not edit directly. ";

    /// <summary>Generates the solution file described by the supplied options.</summary>
    /// <param name="options">Validated generator options.</param>
    public ZoneSolutionResult Generate(ZoneSolutionOptions options)
    {
        var repositories = ZoneRepositoryDiscovery.Discover(options);
        EnsureWritableOutput(options.OutputPath, repositories);

        var outputDirectory = Path.GetDirectoryName(options.OutputPath) ?? Environment.CurrentDirectory;
        var codeWorkspacePath = CodeWorkspacePathFor(options.OutputPath);
        EnsureDistinctOutputs(options.OutputPath, codeWorkspacePath);
        var sourceDocuments = repositories
            .Select(repository => (Repository: repository, Document: SlnxDocument.Read(repository.SolutionPath)))
            .ToArray();
        var devSolutions = GenerateDevSolutions(options, repositories);
        var output = BuildDocument(sourceDocuments, outputDirectory);
        var content = SlnxXml.Format(output);
        var solutionChanged = WriteIfChanged(options.OutputPath, content);
        var codeWorkspaceContent = CodeWorkspaceDocument.Build(repositories, outputDirectory, options.OutputPath);
        var codeWorkspaceChanged = WriteIfChanged(codeWorkspacePath, codeWorkspaceContent);

        return new(
            options.OutputPath,
            codeWorkspacePath,
            solutionChanged,
            codeWorkspaceChanged,
            sourceDocuments
                .Select(source => new ZoneRepositoryResult(source.Repository.Name, source.Repository.SolutionPath, source.Document.Projects.Count))
                .ToArray(),
            devSolutions);
    }

    /// <summary>Derives the generated VS Code workspace path from the generated solution path.</summary>
    public static string CodeWorkspacePathFor(string outputPath) =>
        Path.ChangeExtension(outputPath, ".code-workspace");

    /// <summary>Generates development solutions for each selected consumer repository.</summary>
    private static IReadOnlyList<ZoneDevSolutionResult> GenerateDevSolutions(
        ZoneSolutionOptions options,
        IReadOnlyList<ZoneRepository> repositories)
    {
        var consumers = repositories
            .Where(repository => !IsEngineRepository(repository))
            .ToArray();
        if (consumers.Length == 0)
            return [];

        var engineRepository = FindEngineRepository(options, repositories);
        var generator = new DevSolutionGenerator();
        return consumers
            .Select(consumer =>
            {
                var result = generator.Generate(new DevSolutionOptions(
                    consumer.SolutionPath,
                    engineRepository.SolutionPath,
                    DevSolutionOptions.DefaultOutputPath(consumer.SolutionPath),
                    ["Engine"]));

                return new ZoneDevSolutionResult(
                    consumer.Name,
                    result.OutputPath,
                    result.Changed,
                    result.ConsumerProjectCount,
                    result.EngineProjectCount);
            })
            .ToArray();
    }

    /// <summary>Finds the AlvorKit repository even when the zone output filter omitted it.</summary>
    private static ZoneRepository FindEngineRepository(
        ZoneSolutionOptions options,
        IReadOnlyList<ZoneRepository> repositories)
    {
        var includedEngine = repositories.SingleOrDefault(IsEngineRepository);
        if (includedEngine is not null)
            return includedEngine;

        var engineOptions = new ZoneSolutionOptions(
            options.ZoneRoot,
            options.OutputPath,
            [EngineRepositoryName],
            ListOnly: false);
        return ZoneRepositoryDiscovery.Discover(engineOptions).Single();
    }

    /// <summary>Returns true when the repository is the AlvorKit engine repository.</summary>
    private static bool IsEngineRepository(ZoneRepository repository) =>
        string.Equals(repository.Name, EngineRepositoryName, StringComparison.OrdinalIgnoreCase);

    /// <summary>Creates the combined solution document in output order.</summary>
    private static XDocument BuildDocument(
        IReadOnlyList<(ZoneRepository Repository, SlnxDocument Document)> sourceDocuments,
        string outputDirectory)
    {
        var root = new XElement("Solution", new XComment(GeneratedComment));
        var folders = new Dictionary<string, XElement>(StringComparer.Ordinal);
        var projectPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var source in sourceDocuments)
            AddProjects(root, folders, projectPaths, source.Document.Projects, [source.Repository.Name], outputDirectory);

        return new(root);
    }

    /// <summary>Adds projects to the generated root, grouping all projects under repository-prefixed folders.</summary>
    private static void AddProjects(
        XElement root,
        IDictionary<string, XElement> folders,
        ISet<string> projectPaths,
        IEnumerable<SlnxProject> projects,
        IReadOnlyList<string> folderPrefix,
        string outputDirectory)
    {
        foreach (var project in projects)
        {
            if (!projectPaths.Add(Path.GetFullPath(project.AbsolutePath)))
                continue;

            var folderSegments = SolutionFolderPath.Combine(folderPrefix, project.FolderSegments);
            var element = project.ToElement(outputDirectory);
            EnsureParentFolders(root, folders, folderSegments);
            var folderName = SolutionFolderPath.FormatName(folderSegments);
            folders[folderName].Add(element);
        }
    }

    /// <summary>Ensures every folder prefix exists before adding a project to the deepest folder.</summary>
    private static void EnsureParentFolders(XElement root, IDictionary<string, XElement> folders, IReadOnlyList<string> folderSegments)
    {
        for (var length = 1; length <= folderSegments.Count; length++)
        {
            var name = SolutionFolderPath.FormatName(folderSegments.Take(length).ToArray());
            if (folders.ContainsKey(name))
                continue;

            var folder = new XElement("Folder", new XAttribute("Name", name));
            folders.Add(name, folder);
            root.Add(folder);
        }
    }

    /// <summary>Rejects output paths that would overwrite an input solution.</summary>
    private static void EnsureWritableOutput(string outputPath, IEnumerable<ZoneRepository> repositories)
    {
        foreach (var repository in repositories)
        {
            if (PathText.SamePath(outputPath, repository.SolutionPath))
                throw new InvalidOperationException($"Output path must not overwrite the {repository.Name} solution.");
        }
    }

    /// <summary>Rejects output paths that would make both generated files target the same location.</summary>
    private static void EnsureDistinctOutputs(string outputPath, string codeWorkspacePath)
    {
        if (PathText.SamePath(outputPath, codeWorkspacePath))
            throw new InvalidOperationException("Output path must not already be a .code-workspace file.");
    }

    /// <summary>Writes a generated text file only when its content changed.</summary>
    private static bool WriteIfChanged(string path, string content)
    {
        var changed = !File.Exists(path) || File.ReadAllText(path) != content;
        if (!changed)
            return false;

        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? Environment.CurrentDirectory);
        File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return true;
    }
}
