namespace AlvorKit.Script.Bindgen;

/// <summary>Runs the C header binding pipeline for one configured native library.</summary>
/// <param name="options">Command-line options that control strict validation.</param>
[ExcludeFromCodeCoverage]
internal sealed class CHeaderBindingGenerator(BindgenOptions options)
{
    /// <summary>Primary Clang target used to build the generated binding model.</summary>
    private const string PrimaryTarget = "x86_64-pc-windows-msvc";

    /// <summary>Downloads or locates the native source material required by the binding run.</summary>
    private readonly NativeSourceResolver sourceResolver = new();

    /// <summary>Writes the synthetic translation unit consumed by the C header parser.</summary>
    private readonly TranslationUnitWriter translationUnitWriter = new();

    /// <summary>Checks generated imports against the restored host native package.</summary>
    private readonly BindingExportVerifier exportVerifier = new(options);

    /// <summary>Generates managed and backend projects from a C header bindgen configuration.</summary>
    public async Task GenerateAsync(NativeLibraryBinding library, string? outputRoot)
    {
        await sourceResolver.EnsureSourceAsync(library);
        var translationUnitPath = translationUnitWriter.Write(library);
        try
        {
            EnsureShimFileExists(library);

            Console.WriteLine(
                $"Parsing {library.Config.ImplFile ?? "tu"} + {library.Config.Header} " +
                $"({library.Config.NativeLibrary} {library.Tag})");
            var model = ParsePrimaryModel(library, translationUnitPath);
            model = UpdateSizeofShimIfNeeded(library, translationUnitPath, model);

            Console.WriteLine(
                $"Model: {model.Functions.Count} functions, {model.Enums.Count} enums, " +
                $"{model.Structs.Count} structs, {model.SkippedFunctions.Count} skipped");
            CHeaderLayoutTargetVerifier.ValidateAllTargets(library, translationUnitPath, model);

            new BindingCodeEmitter(library.Config, library.Tag).Emit(
                model,
                library.RepositoryRoot,
                outputRoot,
                library.BindingVersion,
                library.NativeVersion);
            Console.WriteLine(
                $"Emitted {library.Config.ApiProject} and {library.Config.BackendProject} " +
                $"({library.BindingVersion}, native {library.NativeVersion})");

            await exportVerifier.VerifyAsync(library, model);
            SkippedFunctionReporter.Print(model.SkippedFunctions);
            Console.WriteLine();
        }
        finally
        {
            TranslationUnitWriter.Delete(translationUnitPath);
        }
    }

    /// <summary>Parses the primary target model that drives managed code emission.</summary>
    private static BindingModel ParsePrimaryModel(NativeLibraryBinding library, string translationUnitPath) =>
        new CHeaderBindingParser(library.Config, library.Config.ApiClass).Parse(
            translationUnitPath,
            library.IncludeDirectory,
            library.SourceDirectory,
            library.Directory,
            PrimaryTarget);

    /// <summary>Creates the size verification shim placeholder when a configured shim is missing.</summary>
    private static void EnsureShimFileExists(NativeLibraryBinding library)
    {
        if (library.SizeofShimPath is not null && !File.Exists(library.SizeofShimPath))
            File.WriteAllText(library.SizeofShimPath, "// <auto-generated/>" + Environment.NewLine);
    }

    /// <summary>Updates the size shim when allowed, or rejects an out-of-date shim in strict mode.</summary>
    private BindingModel UpdateSizeofShimIfNeeded(
        NativeLibraryBinding library,
        string translationUnitPath,
        BindingModel model)
    {
        if (library.SizeofShimPath is null)
            return model;

        var shim = new BindingCodeEmitter(library.Config, library.Tag).EmitSizeofShim(model);
        if (File.ReadAllText(library.SizeofShimPath) == shim)
            return model;

        if (options.Strict)
            throw new InvalidOperationException(
                $"{library.Config.SizeofShim} is out of date - regenerate locally, rebuild the native library " +
                "and bump version/REVISION.");

        File.WriteAllText(library.SizeofShimPath, shim);
        Console.WriteLine(
            $"Shim: {library.Config.SizeofShim} updated with {model.SizeofTypes.Count} sizeof exports - " +
            "rebuild the native library and bump version/REVISION");
        return ParsePrimaryModel(library, translationUnitPath);
    }
}
