namespace AlvorKit.Script.Bindgen;

/// <summary>Command-line options accepted by the bindgen executable.</summary>
/// <param name="Selection">Requested native library name, or <c>all</c> to generate every configured binding.</param>
/// <param name="Strict">Whether validation gaps should fail the run instead of printing warnings or updating local artifacts.</param>
/// <param name="OutputRoot">
/// Optional repository-relative or absolute directory under <c>out/</c> for generated projects.
/// When omitted, bindgen writes to the non-active default output root.
/// </param>
public sealed record BindgenOptions(string Selection, bool Strict, string? OutputRoot)
{
    /// <summary>Parses bindgen arguments into the selected library, strictness flag, and optional generated-output root.</summary>
    public static BindgenOptions Parse(IReadOnlyList<string> args)
    {
        var selection = new Argument<string>("selection")
        {
            Arity = ArgumentArity.ZeroOrOne,
            Description = "Native library name, or all."
        };
        var strict = new Option<bool>("--strict") { Description = "Fail validation gaps instead of warning." };
        var outputRoot = new Option<string>("--output-root", "--out")
        {
            Description = "Generated output root. Defaults to out/generated/bindgen."
        };
        var setupLocal = new Option<bool>("--setup-local")
        {
            Description = "Shortcut for --output-root out/bindgen to activate local project references."
        };
        var command = new RootCommand("Native binding generator.");
        command.Arguments.Add(selection);
        command.Options.Add(strict);
        command.Options.Add(outputRoot);
        command.Options.Add(setupLocal);
        var result = command.Parse(args.ToArray());
        ThrowIfErrors(result);

        var selected = result.GetValue(selection) ?? "all";
        if (selected.StartsWith("-", StringComparison.Ordinal))
            throw new ArgumentException($"Unrecognized command or argument '{selected}'.");

        var configuredOutputRoot = result.GetValue(outputRoot);
        if (result.GetValue(setupLocal))
        {
            if (result.GetResult(outputRoot) is not null)
                throw new ArgumentException("--setup-local cannot be combined with --output-root.");
            configuredOutputRoot = "out/bindgen";
        }

        return new(
            selected,
            result.GetValue(strict),
            configuredOutputRoot);
    }

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
