namespace AlvorKit.Script.Bindgen;

public static class GeneratedOutput
{
    public static void RecreateDirectory(string directory)
    {
        if (Directory.Exists(directory))
            Directory.Delete(directory, true);
        Directory.CreateDirectory(directory);
    }

    public static string EmitSharedProps() => """
        <!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen. -->
        <Project>
            <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
                <PackageReadmeFile>README.md</PackageReadmeFile>
                <PackageLicenseExpression>MIT</PackageLicenseExpression>
                <GenerateDocumentationFile>true</GenerateDocumentationFile>
                <!-- Upstream docs can miss individual parameter tags, and macro constants rarely
                     have useful comments. Keep warnings focused on generator failures. -->
                <NoWarn>$(NoWarn);CS1573;CS1591</NoWarn>
            </PropertyGroup>

            <PropertyGroup>
                <BaseOutputPath>..\..\..\bin\$(MSBuildProjectName)</BaseOutputPath>
                <BaseIntermediateOutputPath>..\..\..\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
                <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
            </PropertyGroup>

            <ItemGroup>
                <Using Include="System.Runtime.CompilerServices" />
                <Using Include="System.Runtime.InteropServices" />
                <None Include="..\..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
            </ItemGroup>
        </Project>

        """;
}
