<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="BigGustave" Version="1.0.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.Engine\AlvorKit.Engine.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Engine.Loop\AlvorKit.Engine.Loop.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Logging\AlvorKit.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="BigGustave" />
    </ItemGroup>

</Project>
