<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.ECS\AlvorKit.ECS.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.ECS.Indexed.Test" />
    </ItemGroup>
</Project>

