namespace AlvorKit.Windowing.Test;

[TestClass]
public class AgentWindowCommandRunnerTest
{
    /// <summary>Verifies that interactive command lines drive exact updates, input, render, and inspection.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Commands_DriveHost()
    {
        using var host = CreateAgent();
        using var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var keyboard = new Keyboard(loop);
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsTrue(runner.Execute("   "));
        runner.Execute("update 0.25");
        runner.Execute("move 10 20");
        runner.Execute("key Space down");
        runner.Execute("updates 2 0.5 3 4");
        runner.Execute("render 0.125");
        runner.Execute("clipboard hello");
        runner.Execute("text ok");
        runner.Execute("state");

        Assert.AreEqual(new Vec2(16, 28), mouse.Position);
        Assert.IsTrue(keyboard.IsKeyDown(WindowKey.Space));
        Assert.AreEqual(1.25, host.Time);
        Assert.AreEqual(3, host.UpdateCount);
        Assert.AreEqual(1, host.RenderCount);
        Assert.AreEqual("hello", keyboard.Clipboard);
        StringAssert.Contains(output.ToString(), "updates=3");
    }

    /// <summary>Verifies the remaining interactive commands and the reader loop.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Run_HandlesScript()
    {
        using var host = CreateAgent();
        using var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var keyboard = new Keyboard(loop);
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        using var input = new StringReader("""
            step 0.25
            mouse Left down
            mouse Left up
            key A repeat
            key A up
            pan 2 3
            wheel 0 -1
            resize 40 50
            focus false
            visible false
            close
            exit
            """);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Run(input);

        Assert.AreEqual(0.25, host.Time);
        Assert.AreEqual(1, host.UpdateCount);
        Assert.AreEqual(1, host.RenderCount);
        Assert.IsTrue(mouse.IsMainUp());
        Assert.IsTrue(keyboard.IsKeyPressedRepeated(WindowKey.A));
        Assert.AreEqual(new Vec2(2, 3), mouse.Position);
        Assert.AreEqual(new Vec2(0, -1), mouse.Wheel);
        Assert.AreEqual(new Vec2u(40u, 50u), host.ClientSize);
        Assert.IsFalse(host.IsFocused);
        Assert.IsFalse(host.IsVisible);
        Assert.IsTrue(host.IsExiting);
    }

    /// <summary>Verifies that malformed script commands report errors and keep the reader loop alive.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Run_InvalidCommandReportsErrorAndContinues()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        using var input = new StringReader("""
            update
            focus maybe
            state
            exit
            """);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Run(input);

        var text = output.ToString();
        StringAssert.Contains(text, AgentWindowCommandRunner.CommandErrorPrefix + "Required argument missing for command: 'update'.");
        StringAssert.Contains(text, AgentWindowCommandRunner.CommandErrorPrefix + "Cannot parse argument 'maybe' for command 'focus'");
        StringAssert.Contains(text, "updates=0");
    }

    /// <summary>Verifies that an exit command signals the interactive loop to stop.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Exit_ReturnsFalse()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsFalse(runner.Execute("quit"));
    }

    /// <summary>Verifies that command help is generated by System.CommandLine.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Help_WritesGeneratedUsage()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsTrue(runner.Execute("--help"));
        Assert.IsTrue(runner.Execute("help"));

        var text = output.ToString();
        StringAssert.Contains(text, "Usage:");
        StringAssert.Contains(text, "AlvorKit agent window command interface.");
        StringAssert.Contains(text, "screenshot");
        StringAssert.Contains(text, "mouse");
        StringAssert.Contains(text, "text");
    }

    /// <summary>Verifies that screenshot commands are delegated to the host-provided capture callback.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Screenshot_UsesHostCallback()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var calls = 0;
        var capturedPath = string.Empty;
        var runner = new AgentWindowCommandRunner(host, output, (path) =>
        {
            calls++;
            capturedPath = path;
        });

        Assert.IsTrue(runner.Execute("screenshot out\\frame.png"));

        Assert.AreEqual(1, calls);
        Assert.AreEqual("out\\frame.png", capturedPath);
    }

    /// <summary>Verifies that screenshot commands fail clearly when the host did not opt into captures.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_ScreenshotWithoutHost_Throws()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("screenshot out\\frame.png"));
    }

    /// <summary>Verifies that BOM-prefixed scripted input is accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_BomPrefixedCommand_Works()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\uFEFF\uFFFDstate");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that replacement-character-prefixed redirected input is accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_ReplacementPrefixedCommand_Works()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\uFFFDstate");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that mojibake BOM prefixes from redirected console input are accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_MojibakeBomPrefixedCommand_Works()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\u00EF\u00BB\u00BFstate");
        runner.Execute("\u2229\u2557\u2510state");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that unknown commands fail loudly rather than being ignored.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InvalidCommand_Throws()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        var exception = Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("wat"));

        StringAssert.Contains(exception.Message, "wat");
    }

    /// <summary>Verifies that malformed command arguments fail with useful exceptions.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InvalidArguments_Throw()
    {
        using var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update -1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update nope"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 NaN 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 nope 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates nope 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates -1 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("render -1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("render nope"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move nope 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move 1e100 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key A sideways"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key 999 down"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("mouse Left sideways"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("mouse 999 down"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("text"));
    }

    private static AgentGlfwWindowHost CreateAgent() => new(new(new GlNoop()), new(800, 600));
}
