namespace AlvorKit.Windowing.Test;

[TestClass]
public class AgentWindowCommandRunnerTest
{
    /// <summary>Verifies that interactive command lines drive exact updates, input, render, and inspection.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Commands_DriveHost()
    {
        var host = CreateAgent();
        var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var keyboard = new Keyboard(loop);
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsTrue(runner.Execute("   "));
        runner.Execute("update 0.25");
        runner.Execute("move 10 20");
        runner.Execute("key Space down");
        runner.Execute("updates 2 0.5 3 4");
        runner.Execute("render 0.125");
        runner.Execute("clipboard hello");
        runner.Execute("text ok");
        runner.Execute("state");

        Assert.AreEqual(new Vec2(16, 28), mouse.Position);
        Assert.IsTrue(keyboard.IsKeyDown(Keys.Space));
        Assert.AreEqual(1.25, host.Time);
        Assert.AreEqual(3, host.UpdateCount);
        Assert.AreEqual(1, host.RenderCount);
        Assert.AreEqual("hello", host.Clipboard);
        StringAssert.Contains(output.ToString(), "updates=3");
    }

    /// <summary>Verifies the remaining interactive commands and the reader loop.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Run_HandlesScript()
    {
        var host = CreateAgent();
        var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var keyboard = new Keyboard(loop);
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        using var input = new StringReader("""
            step 0.25
            mouse Left down
            mouse Left up
            key A repeat
            key A up
            pan 2 3
            wheel 0 -1
            resize 40 50
            focus false
            visible false
            close
            exit
            """);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Run(input);

        Assert.AreEqual(0.25, host.Time);
        Assert.AreEqual(1, host.UpdateCount);
        Assert.AreEqual(1, host.RenderCount);
        Assert.IsTrue(mouse.IsMainUp());
        Assert.IsTrue(keyboard.IsKeyPressedRepeated(Keys.A));
        Assert.AreEqual(new Vec2(2, 3), mouse.Position);
        Assert.AreEqual(new Vec2(0, -1), mouse.Wheel);
        Assert.AreEqual(new Vec2u(40u, 50u), host.ClientSize);
        Assert.IsFalse(host.IsFocused);
        Assert.IsFalse(host.IsVisible);
        Assert.IsTrue(host.IsExiting);
    }

    /// <summary>Verifies that malformed script commands report errors and keep the reader loop alive.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Run_InvalidCommandReportsErrorAndContinues()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        using var input = new StringReader("""
            update
            focus maybe
            state
            exit
            """);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Run(input);

        var text = output.ToString();
        StringAssert.Contains(text, AgentWindowCommandRunner.CommandErrorPrefix + "Required argument missing for command: 'update'.");
        StringAssert.Contains(text, AgentWindowCommandRunner.CommandErrorPrefix + "Cannot parse argument 'maybe' for command 'focus'");
        StringAssert.Contains(text, "updates=0");
    }

    /// <summary>Verifies that an exit command signals the interactive loop to stop.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Exit_ReturnsFalse()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsFalse(runner.Execute("quit"));
    }

    /// <summary>Verifies that command help is generated by System.CommandLine.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Help_WritesGeneratedUsage()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.IsTrue(runner.Execute("--help"));
        Assert.IsTrue(runner.Execute("help"));

        var text = output.ToString();
        StringAssert.Contains(text, "Usage:");
        StringAssert.Contains(text, "AlvorKit agent window command interface.");
        StringAssert.Contains(text, "screenshot");
        StringAssert.Contains(text, "mouse");
        StringAssert.Contains(text, "text");
        StringAssert.Contains(text, "input-state");
        StringAssert.Contains(text, "click");
        StringAssert.Contains(text, "drag");
    }

    /// <summary>Verifies that input-state reports held input, mouse position, focus, and pending text.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InputState_WritesHeldInput()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("focus false");
        runner.Execute("move 10 20");
        runner.Execute("key D down");
        runner.Execute("mouse Left down");
        runner.Execute("text hello");
        runner.Execute("input-state");
        runner.Execute("update 0.016");
        runner.Execute("mouse Left up");
        runner.Execute("key D up");
        runner.Execute("input-state");

        var text = output.ToString();
        StringAssert.Contains(text, "input focus=false mouse=<10 20> keys=[D] buttons=[Left] text=\"hello\"");
        StringAssert.Contains(text, "input focus=false mouse=<10 20> keys=[] buttons=[] text=\"\"");
    }

    /// <summary>Verifies that input-state uses friendly button names and escapes diagnostic text.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InputState_FormatsAliasesAndEscapedText()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("mouse Right down");
        runner.Execute("mouse Middle down");
        runner.Execute("text slash\\quote");
        host.Agent.EnterText(new Rune('"'));
        runner.Execute("input-state");

        var text = output.ToString();
        StringAssert.Contains(text, "buttons=[Right, Middle]");
        StringAssert.Contains(text, "text=\"slash\\\\quote\\\"\"");
    }

    /// <summary>Verifies that click runs press and release update frames at the requested position.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Click_RunsPressAndReleaseFrames()
    {
        var host = CreateAgent();
        var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var downDuringFirstUpdate = false;
        var upDuringSecondUpdate = false;
        loop.Update += (_) =>
        {
            downDuringFirstUpdate |= host.UpdateCount == 1 && mouse.IsMainDown();
            upDuringSecondUpdate |= host.UpdateCount == 2 && mouse.IsMainUp();
        };
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("click 7 9 0.025");

        Assert.AreEqual(new Vec2(7, 9), mouse.Position);
        Assert.AreEqual(2, host.UpdateCount);
        Assert.AreEqual(0.05, host.Time, 0.0000001);
        Assert.IsTrue(downDuringFirstUpdate);
        Assert.IsTrue(upDuringSecondUpdate);
        Assert.IsTrue(mouse.IsMainUp());
    }

    /// <summary>Verifies that drag interpolates movement over fixed updates and releases the button.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Drag_InterpolatesAndReleases()
    {
        var host = CreateAgent();
        var loop = new WindowLoop(host);
        var mouse = new Mouse(loop);
        var positions = new List<Vec2>();
        loop.Update += (_) => positions.Add(mouse.Position);
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("drag 10 20 16 29 3 0.01");

        Assert.AreEqual(4, host.UpdateCount);
        Assert.AreEqual(0.04, host.Time, 0.0000001);
        CollectionAssert.AreEqual(new[] { new Vec2(12, 23), new Vec2(14, 26), new Vec2(16, 29), new Vec2(16, 29) }, positions);
        Assert.IsTrue(mouse.IsMainUp());
    }

    /// <summary>Verifies that screenshot commands are delegated to the host-provided capture callback.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_Screenshot_UsesHostCallback()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var calls = 0;
        var capturedPath = string.Empty;
        var runner = new AgentWindowCommandRunner(host, output, (path) =>
        {
            calls++;
            capturedPath = path;
        });

        Assert.IsTrue(runner.Execute("screenshot out\\frame.png"));

        Assert.AreEqual(1, calls);
        Assert.AreEqual("out\\frame.png", capturedPath);
    }

    /// <summary>Verifies that screenshot commands fail clearly when the host did not opt into captures.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_ScreenshotWithoutHost_Throws()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("screenshot out\\frame.png"));
    }

    /// <summary>Verifies that BOM-prefixed scripted input is accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_BomPrefixedCommand_Works()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\uFEFF\uFFFDstate");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that replacement-character-prefixed redirected input is accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_ReplacementPrefixedCommand_Works()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\uFFFDstate");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that mojibake BOM prefixes from redirected console input are accepted.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_MojibakeBomPrefixedCommand_Works()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        runner.Execute("\u00EF\u00BB\u00BFstate");
        runner.Execute("\u2229\u2557\u2510state");

        StringAssert.Contains(output.ToString(), "updates=0");
    }

    /// <summary>Verifies that unknown commands fail loudly rather than being ignored.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InvalidCommand_Throws()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        var exception = Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("wat"));

        StringAssert.Contains(exception.Message, "wat");
    }

    /// <summary>Verifies that malformed command arguments fail with useful exceptions.</summary>
    [TestMethod]
    public void AgentWindowCommandRunner_InvalidArguments_Throw()
    {
        var host = CreateAgent();
        using var output = new StringWriter(CultureInfo.InvariantCulture);
        var runner = new AgentWindowCommandRunner(host, output);

        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update -1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update nope"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 NaN 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("update 1 nope 2"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates nope 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("updates -1 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("render -1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("render nope"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move nope 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("move 1e100 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("click"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("click nope 1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("click 1 2 -1"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("drag 1 2 3 4 0 0.016"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("drag 1 2 3 4 1 NaN"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key A sideways"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("key 999 down"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("mouse Left sideways"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("mouse 999 down"));
        Assert.ThrowsException<InvalidOperationException>(() => runner.Execute("text"));
    }

    private AgentGlfwWindowHost CreateAgent()
    {
        var size = new Vec2u(800, 600);
        var glfw = new WindowingTestGlfw(size);
        return new(glfw, glfw.Window, new(new GlNoop()), size);
    }
}
