<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.Interception\AlvorKit.Interception.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Interception.CoreClr\AlvorKit.Interception.CoreClr.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking\AlvorKit.Mocking.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Dynamic\AlvorKit.Mocking.Dynamic.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Interception\AlvorKit.Mocking.Interception.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Interception" />
        <Using Include="AlvorKit.Interception.CoreClr.Advanced" />
        <Using Include="AlvorKit.Mocking" />
        <Using Include="AlvorKit.Mocking.Dynamic" />
        <Using Include="AlvorKit.Mocking.Interception" />
        <Using Include="System.Buffers.Binary" />
        <Using Include="System.Diagnostics" />
        <Using Include="System.Reflection" />
        <Using Include="System.Runtime.CompilerServices" />
        <Using Include="System.Runtime.Loader" />
    </ItemGroup>

</Project>
