namespace AlvorKit;

internal static class ComparisonCatalog
{
    internal static ComparisonCase[] Cases =>
    [
        new("Create1", "AlvorKit", "Sparse", "SparseMutator", "Scalar",
            typeof(RaceAlvorCreate1SparseMutator), RaceAlvorCreate1Measurements.SparseMutator),
        new("Create1", "AlvorKit", "Archetypal", "ArchetypalMutator", "Scalar",
            typeof(RaceAlvorCreate1ArchetypalMutator), RaceAlvorCreate1Measurements.ArchetypalMutator),
        new("Create1", "AlvorKit", "Archetypal", "ArchetypalReusedBuilder", "Scalar",
            typeof(RaceAlvorCreate1ArchetypalReusedBuilder), RaceAlvorCreate1Measurements.ArchetypalReusedBuilder),
        new("Create1", "AlvorKit", "Sparse", "Sparse", "Scalar",
            typeof(RaceAlvorCreate1Sparse), RaceAlvorCreate1Measurements.Sparse),
        new("Create1", "AlvorKit", "Archetypal", "ArchetypalSetters", "Scalar",
            typeof(RaceAlvorCreate1ArchetypalSetters), RaceAlvorCreate1Measurements.ArchetypalSetters),
        new("Create1", "AlvorKit", "Archetypal", "ArchetypalFinalShape", "Scalar",
            typeof(RaceAlvorCreate1ArchetypalFinalShape), RaceAlvorCreate1Measurements.ArchetypalFinalShape),
        new("Create1", "Arch", "", "Default", "Scalar",
            typeof(RaceArchCreate1Default), RaceArchCreate1Measurements.Default),
        new("Create1", "DefaultEcs", "", "Default", "Scalar",
            typeof(RaceDefaultEcsCreate1Default), RaceDefaultEcsCreate1Measurements.Default),
        new("Create1", "Entitas", "", "Default", "Scalar",
            typeof(RaceEntitasCreate1Default), RaceEntitasMeasurements.Create1),
        new("Create1", "Fennecs", "", "Default", "Scalar",
            typeof(RaceFennecsCreate1Default), RaceFennecsCreate1Measurements.Default),
        new("Create1", "FlecsNet", "", "Default", "Scalar",
            typeof(RaceFlecsNetCreate1Default), RaceFlecsNetCreate1Measurements.Default),
        new("Create1", "Frent", "", "Default", "Scalar",
            typeof(RaceFrentCreate1Default), RaceFrentCreate1Measurements.Default),
        new("Create1", "FrifloEngineEcs", "", "Default", "Scalar",
            typeof(RaceFrifloCreate1Default), RaceFrifloCreate1Measurements.Default),
        new("Create1", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehCreate1Direct), RaceMorpehCreate1Measurements.Direct),
        new("Create1", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehCreate1Stash), RaceMorpehCreate1Measurements.Stash),
        new("Create1", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoCreate1Default), RaceSveltoCreate1Measurements.Default),
        new("Create2", "AlvorKit", "Sparse", "SparseMutator", "Scalar",
            typeof(RaceAlvorCreate2SparseMutator), RaceAlvorCreate2Measurements.SparseMutator),
        new("Create2", "AlvorKit", "Archetypal", "ArchetypalMutator", "Scalar",
            typeof(RaceAlvorCreate2ArchetypalMutator), RaceAlvorCreate2Measurements.ArchetypalMutator),
        new("Create2", "AlvorKit", "Archetypal", "ArchetypalReusedBuilder", "Scalar",
            typeof(RaceAlvorCreate2ArchetypalReusedBuilder), RaceAlvorCreate2Measurements.ArchetypalReusedBuilder),
        new("Create2", "AlvorKit", "Sparse", "Sparse", "Scalar",
            typeof(RaceAlvorCreate2Sparse), RaceAlvorCreate2Measurements.Sparse),
        new("Create2", "AlvorKit", "Archetypal", "ArchetypalSetters", "Scalar",
            typeof(RaceAlvorCreate2ArchetypalSetters), RaceAlvorCreate2Measurements.ArchetypalSetters),
        new("Create2", "AlvorKit", "Archetypal", "ArchetypalFinalShape", "Scalar",
            typeof(RaceAlvorCreate2ArchetypalFinalShape), RaceAlvorCreate2Measurements.ArchetypalFinalShape),
        new("Create2", "Arch", "", "Default", "Scalar",
            typeof(RaceArchCreate2Default), RaceArchCreate2Measurements.Default),
        new("Create2", "DefaultEcs", "", "Default", "Scalar",
            typeof(RaceDefaultEcsCreate2Default), RaceDefaultEcsCreate2Measurements.Default),
        new("Create2", "Entitas", "", "Default", "Scalar",
            typeof(RaceEntitasCreate2Default), RaceEntitasMeasurements.Create2),
        new("Create2", "Fennecs", "", "Default", "Scalar",
            typeof(RaceFennecsCreate2Default), RaceFennecsCreate2Measurements.Default),
        new("Create2", "FlecsNet", "", "Default", "Scalar",
            typeof(RaceFlecsNetCreate2Default), RaceFlecsNetCreate2Measurements.Default),
        new("Create2", "Frent", "", "Default", "Scalar",
            typeof(RaceFrentCreate2Default), RaceFrentCreate2Measurements.Default),
        new("Create2", "FrifloEngineEcs", "", "Default", "Scalar",
            typeof(RaceFrifloCreate2Default), RaceFrifloCreate2Measurements.Default),
        new("Create2", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehCreate2Direct), RaceMorpehCreate2Measurements.Direct),
        new("Create2", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehCreate2Stash), RaceMorpehCreate2Measurements.Stash),
        new("Create2", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoCreate2Default), RaceSveltoCreate2Measurements.Default),
        new("Create3", "AlvorKit", "Sparse", "SparseMutator", "Scalar",
            typeof(RaceAlvorCreate3SparseMutator), RaceAlvorCreate3Measurements.SparseMutator),
        new("Create3", "AlvorKit", "Archetypal", "ArchetypalMutator", "Scalar",
            typeof(RaceAlvorCreate3ArchetypalMutator), RaceAlvorCreate3Measurements.ArchetypalMutator),
        new("Create3", "AlvorKit", "Archetypal", "ArchetypalReusedBuilder", "Scalar",
            typeof(RaceAlvorCreate3ArchetypalReusedBuilder), RaceAlvorCreate3Measurements.ArchetypalReusedBuilder),
        new("Create3", "AlvorKit", "Sparse", "Sparse", "Scalar",
            typeof(RaceAlvorCreate3Sparse), RaceAlvorCreate3Measurements.Sparse),
        new("Create3", "AlvorKit", "Archetypal", "ArchetypalSetters", "Scalar",
            typeof(RaceAlvorCreate3ArchetypalSetters), RaceAlvorCreate3Measurements.ArchetypalSetters),
        new("Create3", "AlvorKit", "Archetypal", "ArchetypalFinalShape", "Scalar",
            typeof(RaceAlvorCreate3ArchetypalFinalShape), RaceAlvorCreate3Measurements.ArchetypalFinalShape),
        new("Create3", "Arch", "", "Default", "Scalar",
            typeof(RaceArchCreate3Default), RaceArchCreate3Measurements.Default),
        new("Create3", "DefaultEcs", "", "Default", "Scalar",
            typeof(RaceDefaultEcsCreate3Default), RaceDefaultEcsCreate3Measurements.Default),
        new("Create3", "Entitas", "", "Default", "Scalar",
            typeof(RaceEntitasCreate3Default), RaceEntitasMeasurements.Create3),
        new("Create3", "Fennecs", "", "Default", "Scalar",
            typeof(RaceFennecsCreate3Default), RaceFennecsCreate3Measurements.Default),
        new("Create3", "FlecsNet", "", "Default", "Scalar",
            typeof(RaceFlecsNetCreate3Default), RaceFlecsNetCreate3Measurements.Default),
        new("Create3", "Frent", "", "Default", "Scalar",
            typeof(RaceFrentCreate3Default), RaceFrentCreate3Measurements.Default),
        new("Create3", "FrifloEngineEcs", "", "Default", "Scalar",
            typeof(RaceFrifloCreate3Default), RaceFrifloCreate3Measurements.Default),
        new("Create3", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehCreate3Direct), RaceMorpehCreate3Measurements.Direct),
        new("Create3", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehCreate3Stash), RaceMorpehCreate3Measurements.Stash),
        new("Create3", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoCreate3Default), RaceSveltoCreate3Measurements.Default),
        new("Update1", "AlvorKit", "Sparse", "SparseHandles", "Scalar",
            typeof(RaceAlvorUpdate1SparseHandles), RaceAlvorSparseMeasurements.Update1),
        new("Update1", "AlvorKit", "Archetypal", "DenseHandles", "Scalar",
            typeof(RaceAlvorUpdate1DenseHandles), RaceAlvorUpdate1Measurements.DenseHandles),
        new("Update1", "AlvorKit", "Archetypal", "Query", "Scalar",
            typeof(RaceAlvorUpdate1Query), RaceAlvorUpdate1Measurements.Query),
        new("Update1", "AlvorKit", "Archetypal", "Rows", "Scalar",
            typeof(RaceAlvorUpdate1Rows), RaceAlvorUpdate1Measurements.Rows),
        new("Update1", "AlvorKit", "Archetypal", "Query_SIMD", "Simd",
            typeof(RaceAlvorUpdate1QuerySIMD), RaceAlvorUpdate1Measurements.QuerySIMD),
        new("Update1", "Arch", "", "Scalar", "Scalar",
            typeof(RaceArchUpdate1Scalar), RaceArchUpdate1Measurements.Scalar),
        new("Update1", "Arch", "", "Scalar_SourceGenerated", "Scalar",
            typeof(RaceArchUpdate1ScalarSourceGenerated), RaceArchUpdate1Measurements.ScalarSourceGenerated),
        new("Update1", "DefaultEcs", "", "ComponentSystem_Scalar", "Scalar",
            typeof(RaceDefaultEcsUpdate1ComponentSystemScalar), RaceDefaultEcsUpdate1Measurements.ComponentSystemScalar),
        new("Update1", "DefaultEcs", "", "EntitySetSystem_Scalar", "Scalar",
            typeof(RaceDefaultEcsUpdate1EntitySetSystemScalar), RaceDefaultEcsUpdate1Measurements.EntitySetSystemScalar),
        new("Update1", "Entitas", "", "GroupDirect", "Scalar",
            typeof(RaceEntitasUpdate1GroupDirect), RaceEntitasMeasurements.Update1),
        new("Update1", "Fennecs", "", "ForEach", "Scalar",
            typeof(RaceFennecsUpdate1ForEach), RaceFennecsUpdate1Measurements.ForEach),
        new("Update1", "Fennecs", "", "Raw", "Scalar",
            typeof(RaceFennecsUpdate1Raw), RaceFennecsUpdate1Measurements.Raw),
        new("Update1", "FlecsNet", "", "Each", "Scalar",
            typeof(RaceFlecsNetUpdate1Each), RaceFlecsNetUpdate1Measurements.Each),
        new("Update1", "FlecsNet", "", "Iter", "Scalar",
            typeof(RaceFlecsNetUpdate1Iter), RaceFlecsNetUpdate1Measurements.Iter),
        new("Update1", "Frent", "", "QueryInline", "Scalar",
            typeof(RaceFrentUpdate1QueryInline), RaceFrentUpdate1Measurements.QueryInline),
        new("Update1", "Frent", "", "QueryDelegate", "Scalar",
            typeof(RaceFrentUpdate1QueryDelegate), RaceFrentUpdate1Measurements.QueryDelegate),
        new("Update1", "Frent", "", "Simd", "Simd",
            typeof(RaceFrentUpdate1Simd), RaceFrentUpdate1Measurements.Simd),
        new("Update1", "FrifloEngineEcs", "", "Scalar", "Scalar",
            typeof(RaceFrifloUpdate1Scalar), RaceFrifloUpdate1Measurements.Scalar),
        new("Update1", "FrifloEngineEcs", "", "SIMD_Scalar", "Simd",
            typeof(RaceFrifloUpdate1SIMDScalar), RaceFrifloUpdate1Measurements.SIMDScalar),
        new("Update1", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehUpdate1Direct), RaceMorpehUpdate1Measurements.Direct),
        new("Update1", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehUpdate1Stash), RaceMorpehUpdate1Measurements.Stash),
        new("Update1", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoUpdate1Default), RaceSveltoUpdate1Measurements.Default),
        new("Update2", "AlvorKit", "Sparse", "SparseHandles", "Scalar",
            typeof(RaceAlvorUpdate2SparseHandles), RaceAlvorSparseMeasurements.Update2),
        new("Update2", "AlvorKit", "Archetypal", "DenseHandles", "Scalar",
            typeof(RaceAlvorUpdate2DenseHandles), RaceAlvorUpdate2Measurements.DenseHandles),
        new("Update2", "AlvorKit", "Archetypal", "Query", "Scalar",
            typeof(RaceAlvorUpdate2Query), RaceAlvorUpdate2Measurements.Query),
        new("Update2", "AlvorKit", "Archetypal", "Query_Unrolled4", "Scalar",
            typeof(RaceAlvorUpdate2QueryUnrolled4), RaceAlvorUpdate2Measurements.QueryUnrolled4),
        new("Update2", "AlvorKit", "Archetypal", "Query_Unrolled8", "Scalar",
            typeof(RaceAlvorUpdate2QueryUnrolled8), RaceAlvorUpdate2Measurements.QueryUnrolled8),
        new("Update2", "AlvorKit", "Archetypal", "Rows", "Scalar",
            typeof(RaceAlvorUpdate2Rows), RaceAlvorUpdate2Measurements.Rows),
        new("Update2", "AlvorKit", "Archetypal", "Query_SIMD", "Simd",
            typeof(RaceAlvorUpdate2QuerySIMD), RaceAlvorUpdate2Measurements.QuerySIMD),
        new("Update2", "Arch", "", "Scalar", "Scalar",
            typeof(RaceArchUpdate2Scalar), RaceArchUpdate2Measurements.Scalar),
        new("Update2", "Arch", "", "Scalar_SourceGenerated", "Scalar",
            typeof(RaceArchUpdate2ScalarSourceGenerated), RaceArchUpdate2Measurements.ScalarSourceGenerated),
        new("Update2", "DefaultEcs", "", "Scalar", "Scalar",
            typeof(RaceDefaultEcsUpdate2Scalar), RaceDefaultEcsUpdate2Measurements.Scalar),
        new("Update2", "Entitas", "", "GroupDirect", "Scalar",
            typeof(RaceEntitasUpdate2GroupDirect), RaceEntitasMeasurements.Update2),
        new("Update2", "Fennecs", "", "ForEach", "Scalar",
            typeof(RaceFennecsUpdate2ForEach), RaceFennecsUpdate2Measurements.ForEach),
        new("Update2", "Fennecs", "", "Raw", "Scalar",
            typeof(RaceFennecsUpdate2Raw), RaceFennecsUpdate2Measurements.Raw),
        new("Update2", "FlecsNet", "", "Each", "Scalar",
            typeof(RaceFlecsNetUpdate2Each), RaceFlecsNetUpdate2Measurements.Each),
        new("Update2", "FlecsNet", "", "Iter", "Scalar",
            typeof(RaceFlecsNetUpdate2Iter), RaceFlecsNetUpdate2Measurements.Iter),
        new("Update2", "Frent", "", "QueryInline", "Scalar",
            typeof(RaceFrentUpdate2QueryInline), RaceFrentUpdate2Measurements.QueryInline),
        new("Update2", "Frent", "", "QueryDelegate", "Scalar",
            typeof(RaceFrentUpdate2QueryDelegate), RaceFrentUpdate2Measurements.QueryDelegate),
        new("Update2", "Frent", "", "Simd", "Simd",
            typeof(RaceFrentUpdate2Simd), RaceFrentUpdate2Measurements.Simd),
        new("Update2", "FrifloEngineEcs", "", "Scalar", "Scalar",
            typeof(RaceFrifloUpdate2Scalar), RaceFrifloUpdate2Measurements.Scalar),
        new("Update2", "FrifloEngineEcs", "", "SIMD_Scalar", "Simd",
            typeof(RaceFrifloUpdate2SIMDScalar), RaceFrifloUpdate2Measurements.SIMDScalar),
        new("Update2", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehUpdate2Direct), RaceMorpehUpdate2Measurements.Direct),
        new("Update2", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehUpdate2Stash), RaceMorpehUpdate2Measurements.Stash),
        new("Update2", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoUpdate2Default), RaceSveltoUpdate2Measurements.Default),
        new("Update3", "AlvorKit", "Sparse", "SparseHandles", "Scalar",
            typeof(RaceAlvorUpdate3SparseHandles), RaceAlvorSparseMeasurements.Update3),
        new("Update3", "AlvorKit", "Archetypal", "DenseHandles", "Scalar",
            typeof(RaceAlvorUpdate3DenseHandles), RaceAlvorUpdate3Measurements.DenseHandles),
        new("Update3", "AlvorKit", "Archetypal", "Query", "Scalar",
            typeof(RaceAlvorUpdate3Query), RaceAlvorUpdate3Measurements.Query),
        new("Update3", "AlvorKit", "Archetypal", "Rows", "Scalar",
            typeof(RaceAlvorUpdate3Rows), RaceAlvorUpdate3Measurements.Rows),
        new("Update3", "AlvorKit", "Archetypal", "Query_SIMD", "Simd",
            typeof(RaceAlvorUpdate3QuerySIMD), RaceAlvorUpdate3Measurements.QuerySIMD),
        new("Update3", "Arch", "", "Scalar", "Scalar",
            typeof(RaceArchUpdate3Scalar), RaceArchUpdate3Measurements.Scalar),
        new("Update3", "Arch", "", "Scalar_SourceGenerated", "Scalar",
            typeof(RaceArchUpdate3ScalarSourceGenerated), RaceArchUpdate3Measurements.ScalarSourceGenerated),
        new("Update3", "DefaultEcs", "", "Scalar", "Scalar",
            typeof(RaceDefaultEcsUpdate3Scalar), RaceDefaultEcsUpdate3Measurements.Scalar),
        new("Update3", "Entitas", "", "GroupDirect", "Scalar",
            typeof(RaceEntitasUpdate3GroupDirect), RaceEntitasMeasurements.Update3),
        new("Update3", "Fennecs", "", "ForEach", "Scalar",
            typeof(RaceFennecsUpdate3ForEach), RaceFennecsUpdate3Measurements.ForEach),
        new("Update3", "Fennecs", "", "Raw", "Scalar",
            typeof(RaceFennecsUpdate3Raw), RaceFennecsUpdate3Measurements.Raw),
        new("Update3", "FlecsNet", "", "Each", "Scalar",
            typeof(RaceFlecsNetUpdate3Each), RaceFlecsNetUpdate3Measurements.Each),
        new("Update3", "FlecsNet", "", "Iter", "Scalar",
            typeof(RaceFlecsNetUpdate3Iter), RaceFlecsNetUpdate3Measurements.Iter),
        new("Update3", "Frent", "", "QueryInline", "Scalar",
            typeof(RaceFrentUpdate3QueryInline), RaceFrentUpdate3Measurements.QueryInline),
        new("Update3", "Frent", "", "QueryDelegate", "Scalar",
            typeof(RaceFrentUpdate3QueryDelegate), RaceFrentUpdate3Measurements.QueryDelegate),
        new("Update3", "Frent", "", "Simd", "Simd",
            typeof(RaceFrentUpdate3Simd), RaceFrentUpdate3Measurements.Simd),
        new("Update3", "FrifloEngineEcs", "", "Scalar", "Scalar",
            typeof(RaceFrifloUpdate3Scalar), RaceFrifloUpdate3Measurements.Scalar),
        new("Update3", "FrifloEngineEcs", "", "SIMD_Scalar", "Simd",
            typeof(RaceFrifloUpdate3SIMDScalar), RaceFrifloUpdate3Measurements.SIMDScalar),
        new("Update3", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehUpdate3Direct), RaceMorpehUpdate3Measurements.Direct),
        new("Update3", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehUpdate3Stash), RaceMorpehUpdate3Measurements.Stash),
        new("Update3", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoUpdate3Default), RaceSveltoUpdate3Measurements.Default),
        new("Mixed", "AlvorKit", "Sparse", "SparseHandles", "Scalar",
            typeof(RaceAlvorMixedSparseHandles), RaceAlvorSparseMeasurements.Mixed),
        new("Mixed", "AlvorKit", "Archetypal", "DenseHandles", "Scalar",
            typeof(RaceAlvorMixedDenseHandles), RaceAlvorMixedMeasurements.DenseHandles),
        new("Mixed", "AlvorKit", "Archetypal", "Query", "Scalar",
            typeof(RaceAlvorMixedQuery), RaceAlvorMixedMeasurements.Query),
        new("Mixed", "AlvorKit", "Archetypal", "Rows", "Scalar",
            typeof(RaceAlvorMixedRows), RaceAlvorMixedMeasurements.Rows),
        new("Mixed", "AlvorKit", "Archetypal", "Query_SIMD", "Simd",
            typeof(RaceAlvorMixedQuerySIMD), RaceAlvorMixedMeasurements.QuerySIMD),
        new("Mixed", "Arch", "", "Default", "Scalar",
            typeof(RaceArchMixedDefault), RaceArchMixedMeasurements.Default),
        new("Mixed", "Arch", "", "Scalar_SourceGenerated", "Scalar",
            typeof(RaceArchMixedScalarSourceGenerated), RaceArchMixedMeasurements.ScalarSourceGenerated),
        new("Mixed", "DefaultEcs", "", "Scalar", "Scalar",
            typeof(RaceDefaultEcsMixedScalar), RaceDefaultEcsMixedMeasurements.Scalar),
        new("Mixed", "Entitas", "", "GroupDirect", "Scalar",
            typeof(RaceEntitasMixedGroupDirect), RaceEntitasMeasurements.Mixed),
        new("Mixed", "Fennecs", "", "ForEach", "Scalar",
            typeof(RaceFennecsMixedForEach), RaceFennecsMixedMeasurements.ForEach),
        new("Mixed", "Fennecs", "", "Raw", "Scalar",
            typeof(RaceFennecsMixedRaw), RaceFennecsMixedMeasurements.Raw),
        new("Mixed", "FlecsNet", "", "Each", "Scalar",
            typeof(RaceFlecsNetMixedEach), RaceFlecsNetMixedMeasurements.Each),
        new("Mixed", "FlecsNet", "", "Iter", "Scalar",
            typeof(RaceFlecsNetMixedIter), RaceFlecsNetMixedMeasurements.Iter),
        new("Mixed", "Frent", "", "QueryInline", "Scalar",
            typeof(RaceFrentMixedQueryInline), RaceFrentMixedMeasurements.QueryInline),
        new("Mixed", "Frent", "", "Simd", "Simd",
            typeof(RaceFrentMixedSimd), RaceFrentMixedMeasurements.Simd),
        new("Mixed", "FrifloEngineEcs", "", "Scalar", "Scalar",
            typeof(RaceFrifloMixedScalar), RaceFrifloMixedMeasurements.Scalar),
        new("Mixed", "FrifloEngineEcs", "", "SIMD_Scalar", "Simd",
            typeof(RaceFrifloMixedSIMDScalar), RaceFrifloMixedMeasurements.SIMDScalar),
        new("Mixed", "Morpeh", "", "Direct", "Scalar",
            typeof(RaceMorpehMixedDirect), RaceMorpehMixedMeasurements.Direct),
        new("Mixed", "Morpeh", "", "Stash", "Scalar",
            typeof(RaceMorpehMixedStash), RaceMorpehMixedMeasurements.Stash),
        new("Mixed", "SveltoECS", "", "Default", "Scalar",
            typeof(RaceSveltoMixedDefault), RaceSveltoMixedMeasurements.Default),
    ];
}
