[PlayPause]
KeyPress = "Space"

[StepForward]
KeyPressRepeat = "Right"

[StepBackward]
KeyPressRepeat = "Left"

[ResetScenario]
KeyPress = "R"

[NextScenario]
KeyPress = "Tab"

[PreviousScenario]
KeyPress = "Tab"
Shift = "Down"

[Faster]
KeyPressRepeat = "Equal"

[Slower]
KeyPressRepeat = "Minus"

[UiScaleUp]
KeyPressRepeat = "Equal"
Shift = "Down"

[UiScaleDown]
KeyPressRepeat = "Minus"
Shift = "Down"

[JumpPack]
KeyPress = "P"

[ToggleLabels]
KeyPress = "L"

[TogglePadding]
KeyPress = "A"
