namespace AlvorKit.ECS.Demo.Bench;

/// <summary>Stores one quiescent snapshot of archetypal retained state.</summary>
public readonly record struct EcsArchFootprint(
    int RegisteredFieldCount,
    int FieldCapacity,
    int MaterializedArchCount,
    int ArchCapacity,
    int SignatureMembershipCount,
    int SignatureMembershipCapacity,
    int SignatureIndexCount,
    int SignatureIndexCapacity,
    int SignatureScratchCapacity,
    int SingletonArchCount,
    int SingletonDirectoryCapacity,
    long DirectedStructuralEdgeCount,
    long TransitionCellCapacity,
    int StoredTransitionEdgeCount,
    int TransitionEdgeCapacity,
    int EdgeHeadCapacity,
    int AllocDirectoryCount,
    int AllocDirectoryCapacity,
    long ArchDirectorySlotCapacity,
    long RetainedStateCount,
    long ActiveStateCount,
    long ActiveRowCount,
    long RowCapacity,
    long RowSlack,
    long ComponentBufferCount,
    long ComponentCapacity,
    long CatalogLogicalPayloadBytes,
    long CatalogUsedLogicalPayloadBytes,
    long CatalogSlackLogicalPayloadBytes,
    long RowLogicalPayloadBytes,
    long ColumnLogicalPayloadBytes,
    long ComponentLogicalPayloadBytes,
    long EntUsedLogicalPayloadBytes,
    long EntSlackLogicalPayloadBytes,
    long ComponentUsedLogicalPayloadBytes,
    long ComponentSlackLogicalPayloadBytes,
    long TotalLogicalRetainedBytes,
    long EstimatedManagedBytes,
    long OwnedManagedObjectCount,
    long CatalogManagedObjectCount,
    long StorageManagedObjectCount)
{
    internal static EcsArchFootprint Capture<A>()
    {
        var metrics = EntArchDiagnostics<A>.Capture();
        return new(
            metrics.RegisteredFieldCount,
            metrics.FieldCapacity,
            metrics.MaterializedArchCount,
            metrics.ArchCapacity,
            metrics.SignatureMembershipCount,
            metrics.SignatureMembershipCapacity,
            metrics.SignatureIndexCount,
            metrics.SignatureIndexCapacity,
            metrics.SignatureScratchCapacity,
            metrics.SingletonArchCount,
            metrics.SingletonDirectoryCapacity,
            metrics.DirectedStructuralEdgeCount,
            metrics.TransitionCellCapacity,
            metrics.StoredTransitionEdgeCount,
            metrics.TransitionEdgeCapacity,
            metrics.EdgeHeadCapacity,
            metrics.AllocDirectoryCount,
            metrics.AllocDirectoryCapacity,
            metrics.ArchDirectorySlotCapacity,
            metrics.RetainedStateCount,
            metrics.ActiveStateCount,
            metrics.ActiveRowCount,
            metrics.RowCapacity,
            metrics.RowSlack,
            metrics.ComponentBufferCount,
            metrics.ComponentCapacity,
            metrics.CatalogLogicalPayloadBytes,
            metrics.CatalogUsedLogicalPayloadBytes,
            metrics.CatalogSlackLogicalPayloadBytes,
            metrics.RowLogicalPayloadBytes,
            metrics.ColumnLogicalPayloadBytes,
            metrics.ComponentLogicalPayloadBytes,
            metrics.EntUsedLogicalPayloadBytes,
            metrics.EntSlackLogicalPayloadBytes,
            metrics.ComponentUsedLogicalPayloadBytes,
            metrics.ComponentSlackLogicalPayloadBytes,
            metrics.TotalLogicalRetainedBytes,
            metrics.EstimatedManagedBytes,
            metrics.OwnedManagedObjectCount,
            metrics.CatalogManagedObjectCount,
            metrics.StorageManagedObjectCount);
    }
}
