namespace AlvorKit.ECS.Demo.Bench;

/// <summary>Stores command-line options for the ECS benchmark demo.</summary>
public sealed record EcsBenchOptions(int Operations, int Runs, int Warmups, string? JsonPath)
{
    /// <summary>Creates the command-line surface for the ECS benchmark demo.</summary>
    /// <param name="execute">Action that runs the benchmark with parsed options.</param>
    public static RootCommand CreateRootCommand(Func<EcsBenchOptions, int> execute)
    {
        var quick = new Option<bool>("--quick") { Description = "Use a short agent-friendly sweep." };
        var operations = new Option<string>("--operations") { Description = "Operations per measured run." };
        var runs = new Option<string>("--runs") { Description = "Measured runs per benchmark." };
        var warmups = new Option<string>("--warmups") { Description = "Warmup runs per benchmark." };
        var json = new Option<string>("--json") { Description = "JSON result file." };
        var command = new RootCommand("ECS benchmark demo.");
        command.Options.Add(quick);
        command.Options.Add(operations);
        command.Options.Add(runs);
        command.Options.Add(warmups);
        command.Options.Add(json);
        command.SetAction(parse => execute(CreateOptions(parse, quick, operations, runs, warmups, json)));
        return command;
    }

    /// <summary>Parses benchmark options from command-line arguments.</summary>
    public static EcsBenchOptions Parse(string[] args)
    {
        var quick = new Option<bool>("--quick") { Description = "Use a short agent-friendly sweep." };
        var operations = new Option<string>("--operations") { Description = "Operations per measured run." };
        var runs = new Option<string>("--runs") { Description = "Measured runs per benchmark." };
        var warmups = new Option<string>("--warmups") { Description = "Warmup runs per benchmark." };
        var json = new Option<string>("--json") { Description = "JSON result file." };
        var command = new RootCommand("ECS benchmark demo.");
        command.Options.Add(quick);
        command.Options.Add(operations);
        command.Options.Add(runs);
        command.Options.Add(warmups);
        command.Options.Add(json);
        var result = command.Parse(args);
        ThrowIfErrors(result);

        return CreateOptions(result, quick, operations, runs, warmups, json);
    }

    /// <summary>Creates immutable benchmark options from parsed command-line values.</summary>
    private static EcsBenchOptions CreateOptions(
        ParseResult parse,
        Option<bool> quick,
        Option<string> operations,
        Option<string> runs,
        Option<string> warmups,
        Option<string> json)
    {
        var shortSweep = parse.GetValue(quick);
        return new(
            ParsePositive(parse.GetValue(operations), "--operations", shortSweep ? 1_000_000 : 5_000_000),
            ParsePositive(parse.GetValue(runs), "--runs", shortSweep ? 3 : 7),
            ParseNonNegative(parse.GetValue(warmups), "--warmups", shortSweep ? 1 : 2),
            parse.GetValue(json));
    }

    /// <summary>Parses an optional positive integer option.</summary>
    private static int ParsePositive(string? value, string option, int defaultValue)
    {
        var parsed = ParseNonNegative(value, option, defaultValue);
        return parsed > 0 ? parsed : throw new ArgumentOutOfRangeException(option, "Value must be positive.");
    }

    /// <summary>Parses an optional non-negative integer option.</summary>
    private static int ParseNonNegative(string? value, string option, int defaultValue)
    {
        if (value is null)
            return defaultValue;

        return int.TryParse(value, out var parsed) && parsed >= 0
            ? parsed
            : throw new ArgumentOutOfRangeException(option, "Value must be a non-negative integer.");
    }

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
