namespace AlvorKit.Script.Bindgen;

/// <summary>Absolute directories used for one generated API/backend project pair.</summary>
/// <param name="Root">Directory that receives shared generated project files such as Directory.Build.props.</param>
/// <param name="ApiDirectory">Generated public API project directory.</param>
/// <param name="BackendDirectory">Generated backend project directory.</param>
public sealed record GeneratedProjectLayout(string Root, string ApiDirectory, string BackendDirectory);

/// <summary>Common filesystem and project-file helpers for generated binding output.</summary>
public static class GeneratedOutput
{
    /// <summary>Deletes and recreates a generated directory so stale files cannot survive a run.</summary>
    public static void RecreateDirectory(string directory)
    {
        if (Directory.Exists(directory))
            Directory.Delete(directory, true);
        Directory.CreateDirectory(directory);
    }

    /// <summary>Resolves generated project directories, optionally replacing the configured binding root.</summary>
    public static GeneratedProjectLayout ResolveProjectLayout(
        string repositoryRoot,
        string? outputRoot,
        string apiProject,
        string backendProject)
    {
        if (outputRoot is null)
        {
            var apiDirectory = Path.GetFullPath(Path.Combine(repositoryRoot, apiProject));
            var backendDirectory = Path.GetFullPath(Path.Combine(repositoryRoot, backendProject));
            return new(Path.GetDirectoryName(apiDirectory)!, apiDirectory, backendDirectory);
        }

        var root = Path.GetFullPath(outputRoot);
        return new(
            root,
            Path.Combine(root, ProjectDirectoryName(apiProject)),
            Path.Combine(root, ProjectDirectoryName(backendProject)));
    }

    /// <summary>Emits the shared MSBuild settings used by generated API and backend projects.</summary>
    public static string EmitSharedProps() => """
        <!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen. -->
        <Project>
            <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
                <PackageReadmeFile>README.md</PackageReadmeFile>
                <PackageLicenseExpression>MIT</PackageLicenseExpression>
                <GenerateDocumentationFile>true</GenerateDocumentationFile>
                <!-- Upstream docs can miss individual parameter tags, and macro constants rarely
                     have useful comments. Keep warnings focused on generator failures. -->
                <NoWarn>$(NoWarn);CS1573;CS1591</NoWarn>
            </PropertyGroup>

            <PropertyGroup>
                <BaseOutputPath>..\..\..\bin\$(MSBuildProjectName)</BaseOutputPath>
                <BaseIntermediateOutputPath>..\..\..\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
                <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
            </PropertyGroup>

            <ItemGroup>
                <Using Include="System.Runtime.CompilerServices" />
                <Using Include="System.Runtime.InteropServices" />
                <None Include="..\..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
            </ItemGroup>
        </Project>

        """;

    /// <summary>Returns the configured generated project directory name independent of platform separators.</summary>
    private static string ProjectDirectoryName(string projectPath)
    {
        var name = Path.GetFileName(projectPath.Replace('\\', '/'));
        return name.Length > 0
            ? name
            : throw new ArgumentException("Generated project path must include a directory name.", nameof(projectPath));
    }
}
