namespace AlvorKit.Script.TestCoverage.Test;

/// <summary>Tests for the human-readable Markdown coverage report.</summary>
[TestClass]
public sealed class MarkdownCoverageReportWriterTest
{
    /// <summary>The report includes totals, project failures, unmeasured modules, and artifact paths.</summary>
    [TestMethod]
    public void Write_Report_IncludesHumanReadableSections()
    {
        using var workspace = TempWorkspace.Create();
        var path = workspace.PathFor("coverage-summary.md");
        var summary = new CoverageSummary(
            new(new(1, 2), new(0, 1), new(1, 1)),
            [new("Tool", new(1, 2), new(0, 1), new(1, 1))],
            ["MissingTool"],
            [new("scripts/Tool/Source.cs", 1, 1, 0, [11], [10], [])]);
        var results = new[]
        {
            new TestProjectResult("Tool.Test", "tests/Tool.Test/Tool.Test.csproj", 1, TimeSpan.FromSeconds(1.25), "log", "json", "xml", "info")
        };

        var options = new CoverageOptions("Debug", 100, ["Tool.Test"], ["Tool"], ["xxhash"], 1, true, true, true);

        MarkdownCoverageReportWriter.Write(path, DateTimeOffset.Parse("2026-06-15T00:00:00Z"), options, false, summary, results);
        var markdown = File.ReadAllText(path);

        StringAssert.Contains(markdown, "## Totals");
        StringAssert.Contains(markdown, "Test project filter: `Tool.Test`");
        StringAssert.Contains(markdown, "Source project filter: `Tool`");
        StringAssert.Contains(markdown, "Binding filter: `xxhash`");
        StringAssert.Contains(markdown, "MissingTool");
        StringAssert.Contains(markdown, "FAIL (1)");
        StringAssert.Contains(markdown, "out/coverage/coverage-summary.json");
        StringAssert.Contains(markdown, "out/coverage/html/index.html");
    }

    /// <summary>Agent-mode reports list only artifacts generated by the optimized route.</summary>
    [TestMethod]
    public void Write_AgentMode_ListsJsonArtifactsOnly()
    {
        using var workspace = TempWorkspace.Create();
        var path = workspace.PathFor("coverage-summary.md");
        var summary = new CoverageSummary(new(new(1, 1), new(1, 1), new(1, 1)), [], [], []);
        var options = new CoverageOptions("Debug", 100, [], [], [], 4, false, false, false);

        MarkdownCoverageReportWriter.Write(path, DateTimeOffset.Parse("2026-06-15T00:00:00Z"), options, true, summary, []);
        var markdown = File.ReadAllText(path);

        StringAssert.Contains(markdown, "Per-project JSON reports");
        Assert.IsFalse(markdown.Contains("out/coverage/html/index.html", StringComparison.Ordinal));
        Assert.IsFalse(markdown.Contains("coverage.info", StringComparison.Ordinal));
        Assert.IsFalse(markdown.Contains("coverage.cobertura.xml", StringComparison.Ordinal));
    }

    /// <summary>The report handles passing projects and fully covered files.</summary>
    [TestMethod]
    public void Write_PassingProjectAndCoveredFiles_UsesPassingStatus()
    {
        using var workspace = TempWorkspace.Create();
        var path = workspace.PathFor("coverage-summary.md");
        var summary = new CoverageSummary(
            new(new(1, 1), new(1, 1), new(1, 1)),
            [],
            [],
            [new("scripts/Tool/Source.cs", 0, 0, 0, [], [], [])]);
        var results = new[]
        {
            new TestProjectResult("Tool.Test", "tests/Tool.Test/Tool.Test.csproj", 0, TimeSpan.FromSeconds(1), "log", "json", "xml", "info")
        };
        var options = new CoverageOptions("Debug", 100, [], [], [], 1, false, false, false);

        MarkdownCoverageReportWriter.Write(path, DateTimeOffset.Parse("2026-06-15T00:00:00Z"), options, true, summary, results);
        var markdown = File.ReadAllText(path);

        StringAssert.Contains(markdown, "| Tool.Test | PASS | 1.0s | `log` |");
        Assert.IsFalse(markdown.Contains("scripts/Tool/Source.cs", StringComparison.Ordinal));
    }
}
