namespace AlvorKit.Script.MathsGen;

/// <summary>Command-line options for regenerating AlvorKit.Maths primitive package source.</summary>
/// <param name="OutputRoot">Directory where generated source files should be written.</param>
internal sealed record MathsGenOptions(string OutputRoot)
{
    /// <summary>Creates the command-line surface for the math source generator.</summary>
    /// <param name="repoRoot">Repository root provider used for the default output directory.</param>
    /// <param name="execute">Action that executes generation with parsed options.</param>
    internal static RootCommand CreateRootCommand(Func<string> repoRoot, Func<MathsGenOptions, int> execute)
    {
        var outputRoot = new Option<string>("--output-root", "--output") { Description = "Directory for generated source." };
        var command = new RootCommand("AlvorKit.Maths primitive source generator.");
        command.Options.Add(outputRoot);
        command.SetAction(parse => execute(Options(parse, repoRoot(), outputRoot)));
        return command;
    }

    /// <summary>Parses command-line arguments into generator options.</summary>
    /// <param name="args">Command-line arguments supplied by the caller.</param>
    /// <param name="repoRoot">Repository root used for the default output directory.</param>
    /// <returns>The parsed generator options.</returns>
    internal static MathsGenOptions Parse(IReadOnlyList<string> args, string repoRoot)
    {
        var outputRoot = new Option<string>("--output-root", "--output") { Description = "Directory for generated source." };
        var command = new RootCommand("AlvorKit.Maths primitive source generator.");
        command.Options.Add(outputRoot);
        var result = command.Parse(args.ToArray());
        ThrowIfErrors(result);

        return Options(result, repoRoot, outputRoot);
    }

    /// <summary>Creates generator options from parsed command-line values.</summary>
    private static MathsGenOptions Options(ParseResult parse, string repoRoot, Option<string> outputRoot) =>
        new(Path.GetFullPath(parse.GetValue(outputRoot) ?? Path.Combine(repoRoot, "out", "mathgen")));

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
