namespace AlvorKit.Script.NativeBuild;

/// <summary>Pure parser for the native build command-line arguments.</summary>
internal static class CliParser
{
    /// <summary>Parses arguments into a request or throws a user-facing argument error.</summary>
    public static CliRequest Parse(IReadOnlyList<string> args)
    {
        CliRequest? request = null;
        var result = CreateRootCommand(parsed =>
        {
            request = parsed;
            return Task.FromResult(0);
        }).Parse(args.ToArray());
        ThrowIfErrors(result);
        var exitCode = result.InvokeAsync(SilentInvocation()).GetAwaiter().GetResult();
        if (exitCode != 0)
            throw new ArgumentException($"Command exited with code {exitCode}.");

        return request ?? throw new ArgumentException("A native build command is required.");
    }

    /// <summary>Creates the command tree for the native build runner.</summary>
    /// <param name="execute">Action that executes the parsed request.</param>
    internal static RootCommand CreateRootCommand(Func<CliRequest, Task<int>> execute)
    {
        var root = new RootCommand("AlvorKit native build runner.");
        root.Subcommands.Add(CreateListCommand(execute));
        root.Subcommands.Add(CreateVersionCommand(execute));
        root.Subcommands.Add(CreateBuildCommand(execute));
        return root;
    }

    /// <summary>Creates the library listing command.</summary>
    private static Command CreateListCommand(Func<CliRequest, Task<int>> execute)
    {
        var command = new Command("list", "List libraries with native build manifests.");
        command.SetAction(_ => execute(new(CliCommand.List, Selection: null, Rid: null)));
        return command;
    }

    /// <summary>Creates the native version command.</summary>
    private static Command CreateVersionCommand(Func<CliRequest, Task<int>> execute)
    {
        var library = new Argument<string>("library") { Description = "Native library name." };
        var command = new Command("version", "Print one native package version.");
        command.Arguments.Add(library);
        command.SetAction(parse => execute(new(
            CliCommand.Version,
            parse.GetRequiredValue(library),
            Rid: null)));
        return command;
    }

    /// <summary>Creates the native package build command.</summary>
    private static Command CreateBuildCommand(Func<CliRequest, Task<int>> execute)
    {
        var selection = new Argument<string>("library") { Description = "Native library name, or all." };
        var rid = new Option<string>("--rid") { Description = "Runtime identifier to build." };
        var command = new Command("build", "Build native runtime binaries.");
        command.Arguments.Add(selection);
        command.Options.Add(rid);
        command.SetAction(parse => execute(new(
            CliCommand.Build,
            parse.GetRequiredValue(selection),
            parse.GetValue(rid))));
        return command;
    }

    /// <summary>Creates an invocation configuration that suppresses generated help output during parse tests.</summary>
    private static InvocationConfiguration SilentInvocation() =>
        new() { Output = TextWriter.Null, Error = TextWriter.Null, EnableDefaultExceptionHandler = false };

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
