<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Collections" />
        <Using Include="System.Globalization" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Mocking.Dynamic" />
        <InternalsVisibleTo Include="AlvorKit.Mocking.Emit" />
        <InternalsVisibleTo Include="AlvorKit.Mocking.Interception" />
        <InternalsVisibleTo Include="AlvorKit.Mocking.Performance.Fixture" />
        <InternalsVisibleTo Include="AlvorKit.Mocking.Proxies" />
        <InternalsVisibleTo Include="AlvorKit.Mocking.Test" />
    </ItemGroup>

</Project>
