namespace AlvorKit.Script.Bindgen;

/// <summary>Writes the generated C-header API, backend, native imports, and support projects.</summary>
public sealed class BindingCodeEmitter(BindgenConfig config, string tag)
{
    /// <summary>Emits all generated source and project files for one binding model.</summary>
    public void Emit(BindingModel model, string repoRoot, string bindingVersion, string nativeVersion)
    {
        var context = new BindingEmitterContext(config, tag);
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        GeneratedOutput.RecreateDirectory(apiDirectory);
        GeneratedOutput.RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        var projectEmitter = new BindingProjectEmitter(context);
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), GeneratedOutput.EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), projectEmitter.ApiProject(model, bindingVersion));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"),
            projectEmitter.BackendProject(bindingVersion, nativeVersion, apiProjectName));

        var typeEmitter = new BindingTypeEmitter(context);
        foreach (var enumType in model.Enums)
            File.WriteAllText(Path.Combine(apiDirectory, enumType.ManagedName + ".cs"), typeEmitter.Enum(enumType));
        foreach (var structType in model.Structs)
            File.WriteAllText(Path.Combine(apiDirectory, structType.ManagedName + ".cs"), typeEmitter.Struct(structType));
        foreach (var handle in model.Handles)
            File.WriteAllText(Path.Combine(apiDirectory, handle.ManagedName + ".cs"), typeEmitter.Handle(handle));
        foreach (var callback in model.Delegates)
            File.WriteAllText(Path.Combine(apiDirectory, callback.ManagedName + ".cs"), typeEmitter.Delegate(callback));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), new BindingApiEmitter(context).ApiContract(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Wrapper.cs"), new BindingWrapperEmitter(context).Wrapper(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Noop.cs"), new BindingNoopEmitter(context).Noop(model));
        if (config.SpanExtensions && new BindingSpanExtensionEmitter(context).SpanExtensions(model) is { } spanExtensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), spanExtensions);
        File.WriteAllText(Path.Combine(backendDirectory, config.NativeClass + ".cs"), new BindingNativeImportEmitter(context).NativeImports(model));
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), new BindingBackendEmitter(context).Backend(model));
    }

    /// <summary>Emits native sizeof exports for structs whose allocation size must be queried at runtime.</summary>
    public string EmitSizeofShim(BindingModel model)
    {
        var output = new StringBuilder()
            .AppendLine(BindingEmitterContext.AutoGeneratedMarker)
            .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}).")
            .AppendLine();
        foreach (var nativeType in model.SizeofTypes)
            output.AppendLine($"{config.ShimExport} size_t alvorkit_sizeof_{nativeType}(void) {{ return sizeof({nativeType}); }}");
        return output.ToString();
    }
}
