namespace AlvorKit.Script.NewGame;

/// <summary>Command-line options for creating a sibling AlvorKit game repository.</summary>
internal sealed record NewGameOptions(NewGameName Name, string OutputPath, string AlvorKitRoot)
{
    /// <summary>Creates the command-line surface for the scaffolder.</summary>
    internal static RootCommand CreateRootCommand(
        Func<string> defaultAlvorKitRoot,
        Func<NewGameOptions, Task<int>> execute)
    {
        var name = new Argument<string>("name") { Description = "Game name, such as HelloAlvor." };
        var output = new Option<string?>("--output") { Description = "Output repository directory. Defaults to a sibling of AlvorKit." };
        var alvorKitRoot = new Option<string?>("--alvorkit-root") { Description = "AlvorKit repository root." };
        var command = new RootCommand("Create a new sibling game repository that references AlvorKit source.");
        command.Arguments.Add(name);
        command.Options.Add(output);
        command.Options.Add(alvorKitRoot);
        command.SetAction(parse => execute(Options(parse, defaultAlvorKitRoot, name, output, alvorKitRoot)));
        return command;
    }

    /// <summary>Parses command-line arguments into validated options.</summary>
    public static NewGameOptions Parse(IReadOnlyList<string> args, Func<string> defaultAlvorKitRoot)
    {
        var name = new Argument<string>("name") { Description = "Game name, such as HelloAlvor." };
        var output = new Option<string?>("--output") { Description = "Output repository directory. Defaults to a sibling of AlvorKit." };
        var alvorKitRoot = new Option<string?>("--alvorkit-root") { Description = "AlvorKit repository root." };
        var command = new RootCommand("Create a new sibling game repository that references AlvorKit source.");
        command.Arguments.Add(name);
        command.Options.Add(output);
        command.Options.Add(alvorKitRoot);
        var result = command.Parse(args.ToArray());
        ThrowIfErrors(result);

        return Options(result, defaultAlvorKitRoot, name, output, alvorKitRoot);
    }

    /// <summary>Builds validated options from a parse result and default root provider.</summary>
    private static NewGameOptions Options(
        ParseResult parse,
        Func<string> defaultAlvorKitRoot,
        Argument<string> name,
        Option<string?> output,
        Option<string?> alvorKitRoot)
    {
        var gameName = NewGameName.Parse(parse.GetValue(name) ?? "");
        var root = Path.GetFullPath(parse.GetValue(alvorKitRoot) ?? defaultAlvorKitRoot());
        var outputPath = Path.GetFullPath(parse.GetValue(output) ?? DefaultOutputPath(root, gameName.Identifier));
        return new(gameName, outputPath, root);
    }

    /// <summary>Defaults new game output to an AlvorKit sibling directory.</summary>
    private static string DefaultOutputPath(string alvorKitRoot, string gameName)
    {
        var root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(alvorKitRoot));
        var parent = Path.GetDirectoryName(root) ?? Environment.CurrentDirectory;
        return Path.Combine(parent, gameName);
    }

    /// <summary>Converts parser diagnostics into ordinary exceptions for tests and the CLI boundary.</summary>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
