<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <FastNoise2NativePackageSource>$(AlvorKitRepositoryRoot)bin\AlvorKit.FastNoise2.Native\Release</FastNoise2NativePackageSource>
    </PropertyGroup>

    <PropertyGroup Condition="Exists('$(FastNoise2NativePackageSource)')">
        <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(FastNoise2NativePackageSource)</RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.ECS.Generator\AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\src\AlvorKit.Engine.Loop\AlvorKit.Engine.Loop.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.FastNoise2.Graph\AlvorKit.FastNoise2.Graph.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Graphics2D\AlvorKit.Graphics2D.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Graphics2D.Fonts\AlvorKit.Graphics2D.Fonts.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.UI\AlvorKit.UI.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.UI.Blend\AlvorKit.UI.Blend.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.UI.Generator\AlvorKit.UI.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.UiSyntax">
            <Static>true</Static>
        </Using>
    </ItemGroup>

</Project>
