<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Script.TestCoverage" />
        <InternalsVisibleTo Include="AlvorKit.Script.TestInterception.Test" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference
            Include="AlvorKit.Interception.Profiler.Native"
            Version="0.4.0.4" />
        <PackageReference Include="System.CommandLine" Version="2.0.8" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Collections" />
        <Using Include="System.CommandLine" />
        <Using Include="System.CommandLine.Parsing" />
    </ItemGroup>

</Project>
