<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.Mocking\AlvorKit.Mocking.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Dynamic\AlvorKit.Mocking.Dynamic.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Interception\AlvorKit.Mocking.Interception.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Mocking.Proxies" />
        <Using Include="System.Reflection" />
        <Using Include="System.Reflection.Emit" />
    </ItemGroup>

</Project>
