<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\scripts\AlvorKit.Script.LiveWorkspace\AlvorKit.Script.LiveWorkspace.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Script.LiveWorkspace" />
        <Using Include="System.Security.Cryptography" />
    </ItemGroup>

</Project>
