namespace AlvorKit.LiveCode;

/// <summary>Configures one explicitly enabled, loopback-only LiveCode development endpoint.</summary>
public sealed record LiveCodeHostOptions(string Name)
{
    /// <summary>Gets the discovery directory shared with local LiveCode clients.</summary>
    public string DiscoveryDirectory { get; init; } = LiveCodeDiscovery.DefaultDirectory;

    /// <summary>Gets the loopback port, or zero to request an ephemeral port.</summary>
    public int Port { get; init; }

    /// <summary>Gets additional global-using clauses appended to imports generated by the compilation assembly.</summary>
    public string[] GlobalUsings { get; init; } = [];

    /// <summary>
    /// Gets the assembly whose build-generated global usings define the submission compilation context.
    /// </summary>
    public Assembly? CompilationAssembly { get; init; } = Assembly.GetEntryAssembly();

    /// <summary>Gets the maximum accepted compiled assembly size.</summary>
    public int MaximumAssemblyBytes { get; init; } = 4 * 1024 * 1024;

    /// <summary>Gets the maximum accepted UTF-8 JSON payload size for one bridge invocation.</summary>
    public int MaximumBridgePayloadBytes { get; init; } = 1024 * 1024;

    /// <summary>Gets the maximum number of pending or retained two-phase bridge operations.</summary>
    public int MaximumBridgeOperations { get; init; } = 128;

    /// <summary>Gets whether clients may submit arbitrary compiled C# commands.</summary>
    public bool EnableCodeExecution { get; init; } = true;

    /// <summary>Gets whether clients may discover and invoke predefined structured bridges.</summary>
    public bool EnableBridges { get; init; } = true;

    /// <summary>
    /// Gets the frozen-game inspection configuration, or null to disable the dedicated lane.
    /// </summary>
    public LiveCodeFrozenInspectionOptions? FrozenInspection { get; init; } = new();
}
