namespace AlvorKit.Script.Bindgen;

/// <summary>Writes generated API, native import, and backend implementation projects.</summary>
public sealed class BindingCodeEmitter(BindgenConfig config, string tag)
{
    private const string AutoGeneratedMarker = "// <auto-generated/>";

    public void Emit(BindingModel model, string repoRoot, string version)
    {
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        GeneratedOutput.RecreateDirectory(apiDirectory);
        GeneratedOutput.RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        var unsafeBlocks = config.SpanExtensions || config.SpanReturns.Count > 0
            || model.Functions.Any(function => function.ReturnsCString || function.Parameters.Any(parameter => parameter.HasStringConvenience));
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), GeneratedOutput.EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), EmitApiProject(version, unsafeBlocks));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"), EmitBackendProject(version, apiProjectName));

        foreach (var enumType in model.Enums)
            File.WriteAllText(Path.Combine(apiDirectory, enumType.ManagedName + ".cs"), EmitEnum(enumType));
        foreach (var structType in model.Structs)
            File.WriteAllText(Path.Combine(apiDirectory, structType.ManagedName + ".cs"), EmitStruct(structType));
        foreach (var handle in model.Handles)
            File.WriteAllText(Path.Combine(apiDirectory, handle.ManagedName + ".cs"), EmitHandle(handle));
        foreach (var callback in model.Delegates)
            File.WriteAllText(Path.Combine(apiDirectory, callback.ManagedName + ".cs"), EmitDelegate(callback));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), EmitApiContract(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Wrapper.cs"), EmitWrapper(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Noop.cs"), EmitNoop(model));
        if (config.SpanExtensions && EmitSpanExtensions(model) is { } spanExtensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), spanExtensions);
        File.WriteAllText(Path.Combine(backendDirectory, config.NativeClass + ".cs"), EmitNativeImports(model));
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), EmitBackend(model));
    }

    /// <summary>The C sizeof helpers for caller-allocated types, compiled into the native library.</summary>
    public string EmitSizeofShim(BindingModel model)
    {
        var output = new StringBuilder()
            .AppendLine(AutoGeneratedMarker)
            .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}).")
            .AppendLine();
        foreach (var nativeType in model.SizeofTypes)
            output.AppendLine($"{config.ShimExport} size_t alvorkit_sizeof_{nativeType}(void) {{ return sizeof({nativeType}); }}");
        return output.ToString();
    }

    private string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}). -->";

    private StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine(AutoGeneratedMarker)
        .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}).")
        .AppendLine("#nullable enable annotations")
        .AppendLine();

    private string EmitApiProject(string version, bool unsafeBlocks) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>{(unsafeBlocks ? "\n        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>" : "")}
            </PropertyGroup>

        </Project>

        """;

    private string EmitBackendProject(string version, string apiProjectName) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup Condition="'$(AlvorKitSkipNativePackageReference)' != 'true'">
                <PackageReference Include="{config.Namespace}.Native" Version="{version}" />
            </ItemGroup>

            <ItemGroup>
                <ProjectReference Include="..\{apiProjectName}\{apiProjectName}.csproj" />
            </ItemGroup>

        </Project>

        """;

    private string EmitEnum(BindingEnum enumType)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>{enumType.Documentation ?? $"Maps {enumType.NativeName}."}</summary>");
        if (enumType.IsFlags)
            output.AppendLine("[Flags]");
        output.AppendLine($"public enum {enumType.ManagedName}{(enumType.UnderlyingType == "int" ? "" : " : " + enumType.UnderlyingType)}");
        output.AppendLine("{");
        foreach (var member in enumType.Members)
        {
            if (member.Documentation is not null)
                output.AppendLine($"    /// <summary>{member.Documentation}</summary>");
            output.AppendLine($"    {member.ManagedName} = {member.Value},");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitStruct(BindingStruct structType)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>{structType.Documentation ?? $"Maps {structType.NativeName}."}</summary>");
        output.AppendLine(structType.IsUnion
            ? "[StructLayout(LayoutKind.Explicit)]"
            : "[StructLayout(LayoutKind.Sequential)]");
        output.AppendLine($"public struct {structType.ManagedName}");
        output.AppendLine("{");
        foreach (var field in structType.Fields)
        {
            if (field.Documentation is not null)
                output.AppendLine($"    /// <summary>{field.Documentation}</summary>");
            output.AppendLine($"    {(structType.IsUnion ? "[FieldOffset(0)] " : "")}public {field.ManagedType} {field.ManagedName};");
        }
        foreach (var buffer in structType.NestedBuffers)
        {
            output.AppendLine();
            output.AppendLine($"    /// <summary>A fixed buffer of {buffer.Count} <see cref=\"{buffer.ElementType}\"/> values.</summary>");
            output.AppendLine($"    [InlineArray({buffer.Count})]");
            output.AppendLine($"    public struct {buffer.ManagedName}");
            output.AppendLine("    {");
            output.AppendLine($"        private {buffer.ElementType} element;");
            output.AppendLine("    }");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitHandle(BindingHandle handle)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>An opaque <c>{handle.NativeName}</c> handle; <c>default</c> is the null handle.</summary>");
        output.AppendLine($"public readonly record struct {handle.ManagedName}(nint Handle);");
        return output.ToString();
    }

    private string EmitDelegate(BindingDelegate callback)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>A native callback delegate; install it through the matching <c>Set*Callback</c> method.</summary>");
        output.AppendLine("[UnmanagedFunctionPointer(CallingConvention.Cdecl)]");
        var signature = string.Join(", ", callback.Parameters.Select(parameter => $"{parameter.ManagedType} {parameter.ManagedName}"));
        output.AppendLine($"public delegate {callback.ReturnType} {callback.ManagedName}({signature});");
        return output.ToString();
    }

    private string EmitApiContract(BindingModel model)
    {
        var hasStringConvenience = model.Functions.Any(function => function.Parameters.Any(parameter => parameter.HasStringConvenience));
        var output = SourceHeader();
        if (hasStringConvenience)
            output.AppendLine("using System.Text;").AppendLine();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// {config.ApiSummary}");
        output.AppendLine($"/// Use through a backend implementation, such as {config.BackendClass} from {config.Namespace}.Backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}");
        output.AppendLine("{");
        foreach (var constant in model.Constants)
            output.AppendLine(constant.Value is >= int.MinValue and <= int.MaxValue
                ? $"    public const int {constant.ManagedName} = {constant.Value};"
                : $"    public const long {constant.ManagedName} = {constant.Value};");

        var first = model.Constants.Count == 0;
        foreach (var function in model.Functions)
        {
            if (!first)
                output.AppendLine();
            first = false;
            EmitDocs(output, function);
            output.AppendLine($"    public virtual {function.ReturnType} {function.ManagedName}({Signature(function)}) => throw new NotImplementedException();");
        }
        foreach (var function in model.Functions)
            EmitConvenienceOverloads(output, function);
        EmitCallbackSetters(output, model);
        foreach (var function in model.Functions)
            EmitStringReturn(output, function);
        EmitSpanReturns(output, model);
        if (hasStringConvenience)
            EmitUtf8Helper(output);
        output.AppendLine("}");
        return output.ToString();
    }

    // A const char* return is kept as the raw nint; this adds two overloads that decode it (both keep a
    // distinct signature, since you cannot overload on return type alone), mirroring the OpenGL pipeline:
    // an out-string form (the only allocation is the returned string) and an allocation-free Span<char>
    // form that decodes into the caller's buffer and slices the result.
    private static void EmitStringReturn(StringBuilder output, BindingFunction function)
    {
        if (!function.ReturnsCString)
            return;
        // The out parameters must not clash with an existing one (miniaudio's ma_result_description has a
        // parameter literally named "result"), so each falls back to an underscore-suffixed name.
        var taken = function.Parameters.Select(parameter => parameter.ManagedName.TrimStart('@')).ToHashSet();
        string Unique(string preferred) { while (taken.Contains(preferred)) preferred += "_"; return preferred; }
        var value = Unique("value");
        var destination = Unique("destination");
        var result = Unique("result");

        var leading = function.Parameters.Select(SignatureParameter).ToList();
        var callArguments = string.Join(", ", function.Parameters.Select(Argument));
        var inheritDoc = $"    /// <inheritdoc cref=\"{function.ManagedName}({Cref(function.Parameters)})\"/>";

        var outStringSignature = string.Join(", ", leading.Append($"out string? {value}"));
        output.AppendLine();
        output.AppendLine(inheritDoc);
        output.AppendLine("    /// <remarks>Convenience overload. Decodes the returned C string to a managed string, or null when the pointer is null.</remarks>");
        output.AppendLine($"    public void {function.ManagedName}({outStringSignature}) => {value} = Marshal.PtrToStringUTF8({function.ManagedName}({callArguments}));");

        var spanSignature = string.Join(", ", leading.Append($"Span<char> {destination}").Append($"out ReadOnlySpan<char> {result}"));
        output.AppendLine();
        output.AppendLine(inheritDoc);
        output.AppendLine($"    /// <remarks>Convenience overload. Decodes the returned C string into <paramref name=\"{destination}\"/> (truncated to fit) and sets <paramref name=\"{result}\"/> to the slice written. No allocation.</remarks>");
        output.AppendLine($"    public unsafe void {function.ManagedName}({spanSignature})");
        output.AppendLine("    {");
        output.AppendLine($"        var bytes = MemoryMarshal.CreateReadOnlySpanFromNullTerminated((byte*){function.ManagedName}({callArguments}));");
        output.AppendLine($"        System.Text.Unicode.Utf8.ToUtf16(bytes, {destination}, out _, out var written);");
        output.AppendLine($"        {result} = {destination}[..written];");
        output.AppendLine("    }");
    }

    // A pointer-plus-out-count return surfaced as a garbage-free ReadOnlySpan<T> over the native memory:
    // the trailing out-count parameter is dropped and supplied internally. The raw nint method stays.
    private void EmitSpanReturns(StringBuilder output, BindingModel model)
    {
        foreach (var function in model.Functions)
        {
            if (!config.SpanReturns.TryGetValue(function.NativeName, out var elementType))
                continue;
            var leading = function.Parameters.Take(function.Parameters.Count - 1).ToList();
            var signature = string.Join(", ", leading.Select(SignatureParameter));
            var callArguments = string.Join(", ", leading.Select(Argument).Append("out var count"));
            output.AppendLine();
            output.AppendLine($"    /// <inheritdoc cref=\"{function.ManagedName}({Cref(function.Parameters)})\"/>");
            output.AppendLine("    /// <remarks>Convenience overload. Returns a read-only span over the native memory, supplying the count internally.</remarks>");
            output.AppendLine($"    public unsafe ReadOnlySpan<{elementType}> {function.ManagedName}({signature})");
            output.AppendLine("    {");
            output.AppendLine($"        var pointer = {function.ManagedName}({callArguments});");
            output.AppendLine($"        return pointer == 0 || count <= 0 ? default : new ReadOnlySpan<{elementType}>((void*)pointer, count);");
            output.AppendLine("    }");
        }
    }

    private static string SignatureParameter(BindingParameter parameter) =>
        $"{(parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "")}{parameter.ManagedType} {parameter.ManagedName}";

    private static string Cref(IEnumerable<BindingParameter> parameters) =>
        string.Join(", ", parameters.Select(parameter => (parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "") + parameter.ManagedType));

    // Instance-rooted typed callback setters: each Set*Callback that takes a function pointer gets an
    // overload taking the typed delegate, rooting it on this instance so GLFW's raw pointer never dangles,
    // and forwarding the function pointer to the raw setter.
    private void EmitCallbackSetters(StringBuilder output, BindingModel model)
    {
        var setters = model.Functions.Where(function => function.Parameters.Any(parameter => parameter.CallbackType is not null)).ToList();
        if (setters.Count == 0)
            return;

        output.AppendLine();
        output.AppendLine("    // Allocated on first use, so an instance that never installs a callback stays allocation-free.");
        output.AppendLine("    private Dictionary<(nint Owner, int Slot), Delegate>? rootedCallbacks;");
        output.AppendLine();
        output.AppendLine("    // Roots a callback on this instance and returns the function pointer to install; null clears");
        output.AppendLine("    // it, and replacing a slot drops the previous delegate (which then becomes collectable).");
        output.AppendLine("    private nint RootCallback(nint owner, int slot, Delegate? handler)");
        output.AppendLine("    {");
        output.AppendLine("        if (handler is null) { rootedCallbacks?.Remove((owner, slot)); return 0; }");
        output.AppendLine("        (rootedCallbacks ??= [])[(owner, slot)] = handler;");
        output.AppendLine("        return Marshal.GetFunctionPointerForDelegate(handler);");
        output.AppendLine("    }");

        var slot = 0;
        foreach (var function in setters)
        {
            var callbackParameter = function.Parameters.First(parameter => parameter.CallbackType is not null);
            var ownerParameter = function.Parameters.FirstOrDefault(parameter => model.Handles.Any(handle => handle.ManagedName == parameter.ManagedType));
            var owner = ownerParameter is not null ? $"{ownerParameter.ManagedName}.Handle" : "0";
            var signature = string.Join(", ", function.Parameters.Select(parameter =>
                parameter == callbackParameter ? $"{parameter.CallbackType}? {parameter.ManagedName}" : $"{parameter.ManagedType} {parameter.ManagedName}"));
            var arguments = string.Join(", ", function.Parameters.Select(parameter =>
                parameter == callbackParameter ? $"RootCallback({owner}, {slot}, {parameter.ManagedName})" : parameter.ManagedName));
            var cref = string.Join(", ", function.Parameters.Select(parameter => parameter.ManagedType));
            output.AppendLine();
            output.AppendLine($"    /// <inheritdoc cref=\"{function.ManagedName}({cref})\"/>");
            output.AppendLine("    /// <remarks>Convenience overload. Roots the delegate on this instance and installs its function pointer; pass null to clear it.</remarks>");
            output.AppendLine($"    public void {function.ManagedName}({signature}) => {function.ManagedName}({arguments});");
            slot++;
        }
    }

    // Non-virtual typed overloads that forward to the raw methods: an int parameter that stands for an
    // enum (per config.EnumOverloads) is taken as that enum and cast back; a bool is taken and cast to
    // int; a const char* (raw nint) is taken as a string and marshalled to UTF-8 on the stack; the return
    // may be cast too. A parameter with several candidate types produces one overload per combination.
    private void EmitConvenienceOverloads(StringBuilder output, BindingFunction function)
    {
        var overloads = config.EnumOverloads;
        var perFunction = overloads?.Functions.GetValueOrDefault(function.NativeName);
        var returnEnum = perFunction?.Return;

        var candidateTypes = function.Parameters.Select(parameter =>
        {
            var name = parameter.ManagedName.TrimStart('@');
            if (perFunction?.Params.TryGetValue(name, out var listed) == true && listed.Length > 0)
                return listed;
            if (parameter.Modifier.Length == 0 && overloads?.ByParamName.TryGetValue(name, out var byName) == true)
                return [byName];
            if (parameter.HasStringConvenience)
                return [parameter.ManagedType, "string"];
            return new[] { parameter.ManagedType };
        }).ToList();

        var inheritDoc = $"    /// <inheritdoc cref=\"{function.ManagedName}({string.Join(", ", function.Parameters.Select(parameter => (parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "") + parameter.ManagedType))})\"/>";
        var emitted = new HashSet<string>();
        foreach (var combination in CartesianProduct(candidateTypes))
        {
            var typed = combination.Zip(function.Parameters).ToList();
            if (typed.All(pair => pair.First == pair.Second.ManagedType))
                continue; // identical to the base method; cannot overload on return type alone

            var signature = string.Join(", ", typed.Select(pair =>
                $"{(pair.Second.Modifier.Length > 0 ? pair.Second.Modifier + " " : "")}{pair.First} {pair.Second.ManagedName}"));
            if (!emitted.Add(signature))
                continue;

            var strings = typed.Where(pair => pair.First == "string").Select(pair => pair.Second.ManagedName).ToList();
            var arguments = string.Join(", ", typed.Select(pair =>
                pair.Second.Modifier.Length > 0 ? pair.Second.Modifier + " " + pair.Second.ManagedName
                : pair.First == pair.Second.ManagedType ? pair.Second.ManagedName
                : pair.First == "string" ? $"{pair.Second.ManagedName.TrimStart('@')}Utf8.Pointer"
                : pair.First == "bool" ? $"({pair.Second.ManagedName} ? 1 : 0)"
                : $"(int){pair.Second.ManagedName}"));
            var returnType = returnEnum ?? function.ReturnType;
            var invoke = returnEnum is not null ? $"({returnEnum}){function.ManagedName}({arguments})" : $"{function.ManagedName}({arguments})";

            output.AppendLine(inheritDoc);
            output.AppendLine(strings.Count > 0
                ? "    /// <remarks>Convenience overload. Marshals the string argument to UTF-8 on the stack (native memory for long strings; never the GC heap) and forwards to the underlying method.</remarks>"
                : "    /// <remarks>Convenience overload. Casts the typed arguments and forwards to the underlying method.</remarks>");
            if (strings.Count == 0)
            {
                output.AppendLine($"    public {returnType} {function.ManagedName}({signature}) => {invoke};");
                continue;
            }
            output.AppendLine($"    public {returnType} {function.ManagedName}({signature})");
            output.AppendLine("    {");
            foreach (var name in strings)
                output.AppendLine($"        using var {name.TrimStart('@')}Utf8 = new Utf8({name}, stackalloc byte[256]);");
            output.AppendLine($"        {(returnType == "void" ? invoke : "return " + invoke)};");
            output.AppendLine("    }");
        }
    }

    /// <summary>The stack-first UTF-8 marshalling helper the string convenience overloads use - never the GC heap.</summary>
    private static void EmitUtf8Helper(StringBuilder output)
    {
        output.AppendLine();
        output.AppendLine("    /// <summary>A NUL-terminated UTF-8 copy of a string for interop: stack-backed when short, otherwise native memory freed on Dispose - never on the GC heap.</summary>");
        output.AppendLine("    private readonly unsafe ref struct Utf8");
        output.AppendLine("    {");
        output.AppendLine("        private readonly void* native;");
        output.AppendLine("        /// <summary>Pointer to the NUL-terminated UTF-8 bytes.</summary>");
        output.AppendLine("        public readonly nint Pointer;");
        output.AppendLine();
        output.AppendLine("        public Utf8(string text, Span<byte> stack)");
        output.AppendLine("        {");
        output.AppendLine("            var length = Encoding.UTF8.GetByteCount(text);");
        output.AppendLine("            native = length < stack.Length ? null : NativeMemory.Alloc((nuint)(length + 1));");
        output.AppendLine("            var buffer = native != null ? new Span<byte>(native, length + 1) : stack;");
        output.AppendLine("            Encoding.UTF8.GetBytes(text, buffer);");
        output.AppendLine("            buffer[length] = 0;");
        output.AppendLine("            Pointer = (nint)Unsafe.AsPointer(ref MemoryMarshal.GetReference(buffer));");
        output.AppendLine("        }");
        output.AppendLine();
        output.AppendLine("        public void Dispose() => NativeMemory.Free(native);");
        output.AppendLine("    }");
    }

    private static IEnumerable<string[]> CartesianProduct(List<string[]> lists)
    {
        IEnumerable<string[]> result = [[]];
        foreach (var list in lists)
            result = result.SelectMany(prefix => list.Select(item => (string[])[.. prefix, item]));
        return result;
    }

    /// <summary>
    /// Extension methods on the API class with every span/pointer combination of
    /// the buffer parameters: each detected pointer+length pair (or configured
    /// length-less pointer) can independently become a generic span, pinned for
    /// the duration of the call.
    /// </summary>
    private string? EmitSpanExtensions(BindingModel model)
    {
        var overloads = new StringBuilder();
        foreach (var function in model.Functions)
        {
            var candidates = SpanCandidates(function);
            if (candidates.Count == 0)
                continue;

            var full = (1 << candidates.Count) - 1;
            EmitSpanOverload(overloads, function, candidates, full);
            for (var mask = 1; mask < full; mask++)
                EmitSpanOverload(overloads, function, candidates, mask);
        }
        if (overloads.Length == 0)
            return null;

        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// Span overloads for the <see cref=\"{config.ApiClass}\"/> functions whose pointer+length parameters describe");
        output.AppendLine("/// a buffer consumed during the call: the spans (any unmanaged element) are pinned for the duration of");
        output.AppendLine("/// the call and passed through, in every span/pointer combination.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public static unsafe class {config.ApiClass}Extensions");
        output.AppendLine("{");
        output.Append(overloads);
        output.AppendLine("    // A span holds at most int.MaxValue elements, so the product fits 64-bit nuint for any unmanaged T;");
        output.AppendLine("    // checked() covers 32-bit processes, where a span describing more memory than the address space");
        output.AppendLine("    // would otherwise wrap into a silently wrong length.");
        output.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        output.AppendLine("    private static nuint ByteLength<T>(ReadOnlySpan<T> span) where T : unmanaged =>");
        output.AppendLine("        checked((nuint)span.Length * (nuint)sizeof(T));");
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>The buffer parameters of a function that can become spans: untyped pointers followed by a size_t, plus configured length-less ones.</summary>
    private List<(int Pointer, int? Length)> SpanCandidates(BindingFunction function)
    {
        var candidates = new List<(int Pointer, int? Length)>();
        if (config.SpanSkip.ContainsKey(function.NativeName))
            return candidates;

        var lengthlessParams = config.SpanParams.GetValueOrDefault(function.NativeName, []);
        var parameters = function.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            if (!parameters[i].IsUntypedPointer)
                continue;
            if (i + 1 < parameters.Count && parameters[i + 1].IsSizeT)
                candidates.Add((i, i + 1));
            else if (lengthlessParams.Contains(parameters[i].ManagedName.TrimStart('@')))
                candidates.Add((i, null));
        }
        return candidates;
    }

    private void EmitSpanOverload(StringBuilder output, BindingFunction function, List<(int Pointer, int? Length)> candidates, int mask)
    {
        var spanned = candidates.Where((_, index) => (mask & (1 << index)) != 0).ToList();
        var typeParameterByPointer = spanned.ToDictionary(
            candidate => candidate.Pointer,
            candidate => "T" + TypeParameterName(function.Parameters[candidate.Pointer].ManagedName));
        var pointerByLength = spanned.Where(candidate => candidate.Length is not null)
            .ToDictionary(candidate => candidate.Length!.Value, candidate => candidate.Pointer);

        var instance = config.ApiClass.ToLowerInvariant();
        var signature = new List<string> { $"this {config.ApiClass} {instance}" };
        var arguments = new List<string>();
        foreach (var (parameter, index) in function.Parameters.Select((parameter, index) => (parameter, index)))
        {
            if (typeParameterByPointer.TryGetValue(index, out var typeParameter))
            {
                var spanType = parameter.IsConstPointee ? "ReadOnlySpan" : "Span";
                signature.Add($"{spanType}<{typeParameter}> {parameter.ManagedName}");
                arguments.Add($"(nint){parameter.ManagedName}Ptr");
            }
            else if (pointerByLength.TryGetValue(index, out var pointerIndex))
            {
                var pointerParameter = function.Parameters[pointerIndex];
                arguments.Add($"ByteLength<{typeParameterByPointer[pointerIndex]}>({pointerParameter.ManagedName})");
            }
            else
            {
                var modifier = parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "";
                signature.Add($"{modifier}{parameter.ManagedType} {parameter.ManagedName}");
                arguments.Add($"{modifier}{parameter.ManagedName}");
            }
        }

        var typeParameters = spanned.Select(candidate => typeParameterByPointer[candidate.Pointer]).ToList();
        output.AppendLine($"    /// <inheritdoc cref=\"{config.ApiClass}.{function.ManagedName}\"/>");
        output.Append($"    public static {function.ReturnType} {function.ManagedName}<{string.Join(", ", typeParameters)}>({string.Join(", ", signature)})");
        if (typeParameters.Count == 1)
        {
            output.AppendLine($" where {typeParameters[0]} : unmanaged");
        }
        else
        {
            output.AppendLine();
            foreach (var typeParameter in typeParameters)
                output.AppendLine($"        where {typeParameter} : unmanaged");
        }
        output.AppendLine("    {");
        foreach (var candidate in spanned)
        {
            var parameter = function.Parameters[candidate.Pointer];
            output.AppendLine($"        fixed ({typeParameterByPointer[candidate.Pointer]}* {parameter.ManagedName}Ptr = {parameter.ManagedName})");
        }
        var call = $"{instance}.{function.ManagedName}({string.Join(", ", arguments)})";
        output.AppendLine($"            {(function.ReturnType == "void" ? call : "return " + call)};");
        output.AppendLine("    }");
        output.AppendLine();
    }

    private static string TypeParameterName(string managedParameterName)
    {
        var name = managedParameterName.TrimStart('@');
        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private string EmitNativeImports(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine("[assembly: DisableRuntimeMarshalling]");
        output.AppendLine();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>Raw imports from the {config.NativeLibrary} shared library ({config.Namespace}.Native).</summary>");
        output.AppendLine($"internal static partial class {config.NativeClass}");
        output.AppendLine("{");
        output.AppendLine($"    private const string Lib = \"{config.NativeLibrary}\";");
        foreach (var function in model.Functions)
        {
            // No marshalling: every parameter and the return are blittable interop types, so the source
            // generator emits a direct P/Invoke. String and bool conversions live above this layer.
            output.AppendLine();
            output.AppendLine($"    [LibraryImport(Lib, EntryPoint = \"{function.NativeName}\")]");
            output.AppendLine("    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
            output.AppendLine($"    public static partial {function.ReturnInteropType} {function.ManagedName}({Signature(function, native: true)});");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitBackend(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>Implements <see cref=\"{config.ApiClass}\"/> against the {config.NativeLibrary} shared library.</summary>");
        output.AppendLine($"public class {config.BackendClass} : {config.ApiClass}");
        output.AppendLine("{");
        var first = true;
        foreach (var function in model.Functions)
        {
            if (!first)
                output.AppendLine();
            first = false;
            var arguments = string.Join(", ", function.Parameters.Select(NativeArgument));
            var call = $"{config.NativeClass}.{function.ManagedName}({arguments})";
            var body = function.ReturnType == function.ReturnInteropType ? call
                : function.ReturnType == "bool" ? $"{call} != 0"
                : $"({function.ReturnType}){call}";
            output.AppendLine($"    public override {function.ReturnType} {function.ManagedName}({Signature(function)}) => {body};");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// A forwarding wrapper base: every call delegates to an inner instance. A hand-written
    /// interception layer inherits this and overrides only the calls it cares about.
    /// </summary>
    private string EmitWrapper(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// A <see cref=\"{config.ApiClass}\"/> that forwards every call to an inner instance. Subclass it and");
        output.AppendLine("/// override only the calls you want to intercept; the rest pass straight through.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}Wrapper({config.ApiClass} inner) : {config.ApiClass}");
        output.AppendLine("{");
        output.AppendLine("    /// <summary>The instance each call is forwarded to.</summary>");
        output.AppendLine($"    protected {config.ApiClass} Inner {{ get; }} = inner ?? throw new ArgumentNullException(nameof(inner));");
        foreach (var function in model.Functions)
        {
            output.AppendLine();
            var arguments = string.Join(", ", function.Parameters.Select(Argument));
            output.AppendLine("    /// <inheritdoc/>");
            output.AppendLine($"    public override {function.ReturnType} {function.ManagedName}({Signature(function)}) => Inner.{function.ManagedName}({arguments});");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>A do-nothing implementation that returns default values - a null object for tests or headless use.</summary>
    private string EmitNoop(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>A <see cref=\"{config.ApiClass}\"/> that ignores every call and returns default values - a null object for tests or headless use.</summary>");
        output.AppendLine($"public class {config.ApiClass}Noop : {config.ApiClass}");
        output.AppendLine("{");
        foreach (var function in model.Functions)
            EmitNoopMethod(output, function);
        output.AppendLine("}");
        return output.ToString();
    }

    private static void EmitNoopMethod(StringBuilder output, BindingFunction function)
    {
        var header = $"    public override {function.ReturnType} {function.ManagedName}({Signature(function)})";
        var outParameters = function.Parameters.Where(parameter => parameter.Modifier == "out").ToList();
        if (outParameters.Count == 0)
        {
            output.AppendLine(function.ReturnType == "void" ? header + " { }" : header + " => default;");
            return;
        }
        output.AppendLine(header);
        output.AppendLine("    {");
        foreach (var parameter in outParameters)
            output.AppendLine($"        {parameter.ManagedName} = default;");
        if (function.ReturnType != "void")
            output.AppendLine("        return default;");
        output.AppendLine("    }");
    }

    // The contract/backend/wrapper/noop signature uses the managed type; the native P/Invoke uses the
    // blittable interop type. Neither carries marshalling attributes - the native class stays raw.
    private static string Signature(BindingFunction function, bool native = false) =>
        string.Join(", ", function.Parameters.Select(parameter =>
        {
            var modifier = parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "";
            return $"{modifier}{(native ? parameter.InteropType : parameter.ManagedType)} {parameter.ManagedName}";
        }));

    /// <summary>A forwarded argument in managed terms (for the wrapper passing to the inner instance).</summary>
    private static string Argument(BindingParameter parameter) =>
        (parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "") + parameter.ManagedName;

    /// <summary>An argument for the native call: a bool becomes its underlying integer, other types pass through.</summary>
    private static string NativeArgument(BindingParameter parameter)
    {
        var modifier = parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "";
        if (parameter.ManagedType == parameter.InteropType)
            return modifier + parameter.ManagedName;
        if (parameter.ManagedType == "bool")
            return $"{parameter.ManagedName} ? ({parameter.InteropType})1 : ({parameter.InteropType})0";
        return $"{modifier}({parameter.InteropType}){parameter.ManagedName}";
    }

    private static void EmitDocs(StringBuilder output, BindingFunction function)
    {
        // Lead every summary with the C entry point in <c>, as the OpenGL pipeline does, so the native
        // name is always discoverable - even for functions the header left undocumented.
        if (function.Documentation?.Summary is { } summary)
        {
            var purpose = Capitalize(summary);
            var terminated = purpose.EndsWith('.') || purpose.EndsWith('!') || purpose.EndsWith('?');
            output.AppendLine($"    /// <summary><c>{function.NativeName}</c> - {purpose}{(terminated ? "" : ".")}</summary>");
        }
        else
        {
            output.AppendLine($"    /// <summary><c>{function.NativeName}</c></summary>");
        }

        if (function.Documentation is not { } documentation)
            return;
        foreach (var parameter in function.Parameters)
            if (documentation.Parameters.TryGetValue(parameter.ManagedName.TrimStart('@'), out var text))
                output.AppendLine($"    /// <param name=\"{parameter.ManagedName.TrimStart('@')}\">{text}</param>");
        if (documentation.Returns is not null)
            output.AppendLine($"    /// <returns>{documentation.Returns}</returns>");
        if (documentation.Remarks is not null)
            output.AppendLine($"    /// <remarks>{documentation.Remarks}</remarks>");
    }

    private static string Capitalize(string text) =>
        text.Length > 0 && char.IsAsciiLetterLower(text[0]) ? char.ToUpperInvariant(text[0]) + text[1..] : text;
}
