namespace AlvorKit.Script.Bindgen;

/// <summary>Shared configuration and source-header helpers for generated binding files.</summary>
/// <param name="Config">Binding generation configuration.</param>
/// <param name="Tag">Native source tag used in generated banners.</param>
internal sealed record BindingEmitterContext(BindgenConfig Config, string Tag)
{
    /// <summary>Marker written to generated source files.</summary>
    public const string AutoGeneratedMarker = "// <auto-generated/>";

    /// <summary>Returns the XML comment banner for generated project files.</summary>
    public string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {Config.NativeLibrary} {Tag} ({Config.Header}). -->";

    /// <summary>Returns the standard generated C# source header.</summary>
    public StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine(AutoGeneratedMarker)
        .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {Config.NativeLibrary} {Tag} ({Config.Header}).")
        .AppendLine("#nullable enable annotations")
        .AppendLine();
}
