namespace AlvorKit.Script.Bindgen;

/// <summary>Writes the generated OpenGL API contract and proc-loading backend projects.</summary>
public sealed class GlCodeEmitter(BindgenConfig config, string tag, string docTag)
{
    public void Emit(GlBindingModel model, string repoRoot, string version)
    {
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        GeneratedOutput.RecreateDirectory(apiDirectory);
        GeneratedOutput.RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), GeneratedOutput.EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), EmitApiProject(version));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"), EmitBackendProject(version, apiProjectName));

        foreach (var group in model.Groups)
            File.WriteAllText(Path.Combine(apiDirectory, group.ManagedName + ".cs"), EmitEnum(group, catchAll: false));
        File.WriteAllText(Path.Combine(apiDirectory, model.AllTokens.ManagedName + ".cs"), EmitEnum(model.AllTokens, catchAll: true));
        if (model.HandleTypes.Count > 0)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Handles.cs"), EmitHandles(model));
        foreach (var callback in model.Delegates)
            File.WriteAllText(Path.Combine(apiDirectory, callback.ManagedName + ".cs"), EmitDelegate(callback));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), EmitApiContract(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Wrapper.cs"), EmitWrapper(model));
        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Noop.cs"), EmitNoop(model));
        if (model.WideConstants.Count > 0)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Constants.cs"), EmitConstants(model));
        if (new GlExtensionsEmitter(config).Emit(model, SourceHeader()) is { } extensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), extensions);
        File.WriteAllText(Path.Combine(apiDirectory, "THIRD-PARTY-NOTICES.txt"), EmitThirdPartyNotices(model));
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), EmitBackend(model));
    }

    private string Origin =>
        $"the OpenGL registry at {tag[..Math.Min(12, tag.Length)]} ({config.GlApi} {config.GlVersion} {config.GlProfile})";

    private string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {Origin}. -->";

    private StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine("// <auto-generated/>")
        .AppendLine("#nullable enable")
        .AppendLine();

    /// <summary>
    /// "GL 4.2, GL ES 3.1" for items in both APIs, just the desktop part when ES has it not.
    /// A non-numeric desktop value is an extension name and is shown verbatim.
    /// </summary>
    private static string AvailabilityText(GlAvailability availability)
    {
        var desktop = char.IsAsciiDigit(availability.Gl[0]) ? $"GL {availability.Gl}" : availability.Gl;
        return availability.GlEs is null ? desktop : $"{desktop}, GL ES {availability.GlEs}";
    }

    private string EmitApiProject(string version) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <None Include="THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
            </ItemGroup>

        </Project>

        """;

    /// <summary>No .Native package: the platform's GL driver is the native library.</summary>
    private string EmitBackendProject(string version, string apiProjectName) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <ProjectReference Include="..\{apiProjectName}\{apiProjectName}.csproj" />
            </ItemGroup>

        </Project>

        """;

    private string EmitEnum(GlEnumGroup group, bool catchAll)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        if (catchAll)
            output.AppendLine($"/// <summary>Every {config.GlApi} {config.GlVersion} {config.GlProfile} token: the fallback type for parameters without a typed group.</summary>");
        if (group.IsFlags)
            output.AppendLine("[Flags]");
        output.AppendLine($"public enum {group.ManagedName} : uint");
        output.AppendLine("{");
        foreach (var member in group.Members)
        {
            var membership = catchAll && member.Groups.Count > 0
                ? $" See {string.Join(", ", member.Groups.Select(group => $"<see cref=\"{group}\"/>"))}."
                : "";
            output.AppendLine($"    /// <summary>{member.NativeName} ({AvailabilityText(member.Availability)}).{membership}</summary>");
            output.AppendLine($"    {member.ManagedName} = 0x{member.Value:X4},");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// The strongly-typed handle structs: a <c>readonly record struct</c> over the raw object name
    /// per registry handle class, each widening implicitly to the generic handle, with explicit
    /// conversions to and from <c>uint</c>.
    /// </summary>
    private string EmitHandles(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        foreach (var handle in model.HandleTypes)
        {
            output.AppendLine();
            output.AppendLine(handle == "GlHandle"
                ? "/// <summary>A strongly-typed handle to any OpenGL object; every specific handle widens to it.</summary>"
                : "/// <summary>A strongly-typed OpenGL object handle.</summary>");
            output.AppendLine($"public readonly record struct {handle}(uint Handle)");
            output.AppendLine("{");
            if (handle != "GlHandle")
            {
                output.AppendLine("    /// <summary>Widens to the generic <see cref=\"GlHandle\"/> handle.</summary>");
                output.AppendLine($"    public static implicit operator GlHandle({handle} handle) => new(handle.Handle);");
            }
            output.AppendLine("    /// <summary>The raw object name. Explicit: a handle never implicitly becomes an integer.</summary>");
            output.AppendLine($"    public static explicit operator uint({handle} handle) => handle.Handle;");
            output.AppendLine("    /// <summary>Wraps a raw object name. Explicit: an integer is never implicitly a handle.</summary>");
            output.AppendLine($"    public static explicit operator {handle}(uint handle) => new(handle);");
            output.AppendLine("}");
        }
        return output.ToString();
    }

    private string EmitApiContract(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// {config.ApiSummary}");
        output.AppendLine($"/// Use through a backend implementation, such as {config.BackendClass} from {config.Namespace}.Backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public partial class {config.ApiClass}");
        output.AppendLine("{");
        var first = true;
        foreach (var command in model.Commands)
        {
            if (!first)
                output.AppendLine();
            first = false;
            EmitCommandDocs(output, command);
            output.AppendLine($"    public virtual {command.ReturnType} {command.ManagedName}({Signature(command)}) => throw new NotImplementedException();");
        }
        EmitCallbackSetters(output, model);
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// A native callback delegate (GLDEBUGPROC as GlDebugProc). Its parameters are typed like the
    /// commands - enums where the config groups them, raw nint pointers otherwise - and it is
    /// blittable, so the typed setter can hand its function pointer straight to the driver.
    /// </summary>
    private string EmitDelegate(GlDelegate callback)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>An OpenGL callback (<c>{callback.NativeName}</c>); install it through the matching setter, which roots it on the instance.</summary>");
        output.AppendLine("[UnmanagedFunctionPointer(CallingConvention.Winapi)]");
        var signature = string.Join(", ", callback.Parameters.Select(parameter => $"{parameter.ManagedType} {parameter.ManagedName}"));
        output.AppendLine($"public delegate {callback.ReturnType} {callback.ManagedName}({signature});");
        return output.ToString();
    }

    // Instance-rooted typed callback setters: each callback-taking entry point (glDebugMessageCallback)
    // gets an overload taking the typed delegate, rooting it on this instance so the driver's raw
    // function pointer never dangles, and forwarding the function pointer to the raw method.
    private void EmitCallbackSetters(StringBuilder output, GlBindingModel model)
    {
        var setters = model.Commands.Where(command => command.Parameters.Any(parameter => parameter.CallbackType is not null)).ToList();
        if (setters.Count == 0)
            return;

        output.AppendLine();
        output.AppendLine("    // Allocated on first use, so an instance that never installs a callback stays allocation-free.");
        output.AppendLine("    private Dictionary<int, Delegate>? rootedCallbacks;");
        output.AppendLine();
        output.AppendLine("    // Roots a callback on this instance and returns the function pointer to install; null clears");
        output.AppendLine("    // it, and replacing a slot drops the previous delegate (which then becomes collectable).");
        output.AppendLine("    private nint RootCallback(int slot, Delegate? handler)");
        output.AppendLine("    {");
        output.AppendLine("        if (handler is null) { rootedCallbacks?.Remove(slot); return 0; }");
        output.AppendLine("        (rootedCallbacks ??= [])[slot] = handler;");
        output.AppendLine("        return Marshal.GetFunctionPointerForDelegate(handler);");
        output.AppendLine("    }");

        var slot = 0;
        foreach (var command in setters)
        {
            var callbackParameter = command.Parameters.First(parameter => parameter.CallbackType is not null);
            var signature = string.Join(", ", command.Parameters.Select(parameter =>
                parameter == callbackParameter ? $"{parameter.CallbackType}? {parameter.ManagedName}" : $"{parameter.ManagedType} {parameter.ManagedName}"));
            var arguments = string.Join(", ", command.Parameters.Select(parameter =>
                parameter == callbackParameter ? $"RootCallback({slot}, {parameter.ManagedName})" : parameter.ManagedName));
            var cref = string.Join(", ", command.Parameters.Select(parameter => parameter.ManagedType));
            output.AppendLine();
            output.AppendLine($"    /// <inheritdoc cref=\"{command.ManagedName}({cref})\"/>");
            output.AppendLine("    /// <remarks>Convenience overload. Roots the delegate on this instance and installs its function pointer; pass null to clear it.</remarks>");
            output.AppendLine($"    public void {command.ManagedName}({signature}) => {command.ManagedName}({arguments});");
            slot++;
        }
    }

    /// <summary>
    /// The tokens whose values overflow the uint-backed enums (GL_TIMEOUT_IGNORED): genuine 64-bit
    /// sentinel numbers rather than GLenum members, so they are plain constants in their own class.
    /// </summary>
    private string EmitConstants(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>OpenGL tokens whose values are too wide for the uint-backed {config.ApiClass} enums.</summary>");
        output.AppendLine($"public static class {config.ApiClass}Constants");
        output.AppendLine("{");
        var first = true;
        foreach (var constant in model.WideConstants)
        {
            if (!first)
                output.AppendLine();
            first = false;
            output.AppendLine($"    /// <summary>{constant.NativeName} ({AvailabilityText(constant.Availability)}).</summary>");
            output.AppendLine($"    public const ulong {constant.ManagedName} = 0x{constant.Value:X};");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// The GL entry point, its availability and the reference-page purpose as the summary, then a
    /// param tag for each parameter the page documents. Commands without a reference page get just
    /// the entry point and availability.
    /// </summary>
    private void EmitCommandDocs(StringBuilder output, GlCommand command)
    {
        var availability = AvailabilityText(command.Availability);
        if (command.Documentation?.Summary is { } summary)
        {
            var purpose = Capitalize(summary);
            var terminated = purpose.EndsWith('.') || purpose.EndsWith('!') || purpose.EndsWith('?');
            output.AppendLine($"    /// <summary><c>{command.NativeName}</c> ({availability}) - {purpose}{(terminated ? "" : ".")}</summary>");
        }
        else
        {
            output.AppendLine($"    /// <summary><c>{command.NativeName}</c> ({availability})</summary>");
        }

        if (command.Documentation is { } documentation)
            foreach (var parameter in command.Parameters)
                if (documentation.Parameters.TryGetValue(parameter.NativeName, out var text))
                    output.AppendLine($"    /// <param name=\"{parameter.NativeName}\">{text}</param>");
    }

    private static string Capitalize(string text) =>
        text.Length > 0 && char.IsAsciiLetterLower(text[0]) ? char.ToUpperInvariant(text[0]) + text[1..] : text;

    /// <summary>
    /// Attribution for the reference-page prose imported into the XML docs, required by the SGI
    /// Free Software License B the OpenGL reference pages are published under.
    /// </summary>
    private string EmitThirdPartyNotices(GlBindingModel model)
    {
        var documented = model.Commands.Count(command => command.Documentation is not null);
        if (documented == 0)
            return $"{config.Namespace} contains no third-party content." + Environment.NewLine;

        var shortDocTag = docTag.Length >= 12 ? docTag[..12] : docTag;
        return $"""
            {config.Namespace} third-party notices
            ===================================

            The XML documentation comments on the {config.ApiClass} commands ({documented} of
            {model.Commands.Count}) are derived from the Khronos OpenGL reference pages (the gl4
            directory of the OpenGL-Refpages repository, commit {shortDocTag}).

            The reference pages are copyright their respective authors and are made available by
            The Khronos Group under the SGI Free Software License B, version 2.0. Portions are
            copyright (c) 1991-2006 Silicon Graphics, Inc. and (c) 2010-2014 The Khronos Group Inc.

            Source and license text:
              https://github.com/KhronosGroup/OpenGL-Refpages
              https://www.khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt

            """;
    }

    /// <summary>
    /// A forwarding wrapper base: every command delegates to an inner instance. A hand-written
    /// interception layer (validation, tracing, resource tracking) inherits this and overrides only
    /// the calls it cares about, letting the rest pass through.
    /// </summary>
    private string EmitWrapper(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// A <see cref=\"{config.ApiClass}\"/> that forwards every call to an inner instance. Subclass it and");
        output.AppendLine("/// override only the calls you want to intercept (to validate, trace or track resources); the");
        output.AppendLine("/// rest pass straight through. This is the base for a layer that wraps a backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}Wrapper({config.ApiClass} inner) : {config.ApiClass}");
        output.AppendLine("{");
        output.AppendLine("    /// <summary>The instance each call is forwarded to.</summary>");
        output.AppendLine($"    protected {config.ApiClass} Inner {{ get; }} = inner ?? throw new ArgumentNullException(nameof(inner));");
        foreach (var command in model.Commands)
        {
            output.AppendLine();
            var arguments = string.Join(", ", command.Parameters.Select(parameter => parameter.ManagedName));
            output.AppendLine("    /// <inheritdoc/>");
            output.AppendLine($"    public override {command.ReturnType} {command.ManagedName}({Signature(command)}) => Inner.{command.ManagedName}({arguments});");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>A do-nothing implementation that returns default values - a null object for tests or headless use.</summary>
    private string EmitNoop(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>A <see cref=\"{config.ApiClass}\"/> that ignores every call and returns default values - a null object for tests or headless use.</summary>");
        output.AppendLine($"public class {config.ApiClass}Noop : {config.ApiClass}");
        output.AppendLine("{");
        foreach (var command in model.Commands)
            output.AppendLine(command.ReturnType == "void"
                ? $"    public override void {command.ManagedName}({Signature(command)}) {{ }}"
                : $"    public override {command.ReturnType} {command.ManagedName}({Signature(command)}) => default;");
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitBackend(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// Implements <see cref=\"{config.ApiClass}\"/> over function pointers resolved from the current OpenGL context.");
        output.AppendLine("/// Construct it with a proc loader once the context is current.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public unsafe class {config.BackendClass} : {config.ApiClass}");
        output.AppendLine("{");
        foreach (var command in model.Commands)
            output.AppendLine($"    private readonly {DelegateType(command)} {command.NativeName};");

        output.AppendLine();
        output.AppendLine("    /// <summary>");
        output.AppendLine("    /// Resolves every entry point through <paramref name=\"getProcAddress\"/> (such as");
        output.AppendLine("    /// Glfw.GetProcAddress), which must be called with the OpenGL context current.");
        output.AppendLine("    /// Entry points the context does not provide stay unresolved: calling one throws");
        output.AppendLine("    /// <see cref=\"EntryPointNotFoundException\"/> naming the function.");
        output.AppendLine("    /// </summary>");
        output.AppendLine($"    public {config.BackendClass}(Func<string, nint> getProcAddress)");
        output.AppendLine("    {");
        foreach (var command in model.Commands)
            output.AppendLine($"        {command.NativeName} = ({DelegateType(command)})getProcAddress(\"{command.NativeName}\");");
        output.AppendLine("    }");

        foreach (var command in model.Commands)
        {
            output.AppendLine();
            output.AppendLine($"    public override {command.ReturnType} {command.ManagedName}({Signature(command)})");
            output.AppendLine("    {");
            output.AppendLine($"        if ({command.NativeName} is null) throw NotLoaded(\"{command.NativeName}\");");
            output.AppendLine($"        {Call(command)}");
            output.AppendLine("    }");
        }

        output.AppendLine();
        output.AppendLine("    private static EntryPointNotFoundException NotLoaded(string entryPoint) =>");
        output.AppendLine("        new($\"OpenGL entry point not available in the current context: {entryPoint} (the proc loader did not provide it - the function is not in the active GL version or driver).\");");
        output.AppendLine("}");
        return output.ToString();
    }

    private static string Signature(GlCommand command) =>
        string.Join(", ", command.Parameters.Select(parameter => $"{parameter.ManagedType} {parameter.ManagedName}"));

    /// <summary>The function pointer type at the interop boundary: enums travel as uint, bool as byte.</summary>
    private static string DelegateType(GlCommand command) =>
        $"delegate* unmanaged<{string.Join(", ", command.Parameters.Select(parameter => parameter.InteropType).Append(command.ReturnInteropType))}>";

    private static string Call(GlCommand command)
    {
        var arguments = command.Parameters.Select(parameter =>
            parameter.ManagedType == parameter.InteropType ? parameter.ManagedName
            : parameter.ManagedType == "bool" ? $"{parameter.ManagedName} ? (byte)1 : (byte)0"
            : $"({parameter.InteropType}){parameter.ManagedName}");
        var call = $"{command.NativeName}({string.Join(", ", arguments)})";

        if (command.ReturnType == "void")
            return $"{call};";
        if (command.ReturnType == command.ReturnInteropType)
            return $"return {call};";
        return command.ReturnType == "bool"
            ? $"return {call} != 0;"
            : $"return ({command.ReturnType}){call};";
    }
}
