<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Injection\AlvorKit.Injection.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Logging\AlvorKit.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Injection" />
        <Using Include="AlvorKit.Logging" />
    </ItemGroup>

</Project>
