<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Script.Lint.Test" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="System.CommandLine" Version="2.0.8" />
        <ProjectReference Include="..\AlvorKit.Script.Workspace\AlvorKit.Script.Workspace.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.CodeAnalysis" />
        <Using Include="Microsoft.CodeAnalysis.CSharp" />
        <Using Include="Microsoft.CodeAnalysis.CSharp.Syntax" />
        <Using Include="System.CommandLine" />
        <Using Include="System.CommandLine.Parsing" />
    </ItemGroup>

</Project>
