<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.Maths\AlvorKit.Maths.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Maths" />
        <InternalsVisibleTo Include="AlvorKit.Windowing.Test" />
        <InternalsVisibleTo Include="AlvorKit.Windowing.Agent" />
        <InternalsVisibleTo Include="AlvorKit.Engine.LiveCode" />
    </ItemGroup>

</Project>
