<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\AlvorStarter.App\AlvorStarter.App.csproj" />
        <ProjectReference Include="..\AlvorStarter.App.Frontend\AlvorStarter.App.Frontend.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.ECS.Generator\AlvorKit.ECS.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.Engine.Loop\AlvorKit.Engine.Loop.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI\AlvorKit.UI.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI.Blend\AlvorKit.UI.Blend.csproj" />
        <ProjectReference Include="$(AlvorKitRoot)src\AlvorKit.UI.Generator\AlvorKit.UI.Generator.csproj"
            OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.UiSyntax" Static="true" />
    </ItemGroup>

</Project>
