<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <FastNoise2NativePackageSource>$(AlvorKitRepositoryRoot)bin\AlvorKit.FastNoise2.Native\Release</FastNoise2NativePackageSource>
    </PropertyGroup>

    <PropertyGroup Condition="Exists('$(FastNoise2NativePackageSource)')">
        <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(FastNoise2NativePackageSource)</RestoreAdditionalProjectSources>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.Engine.Loop\AlvorKit.Engine.Loop.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.FastNoise2.Graph\AlvorKit.FastNoise2.Graph.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Graphics2D\AlvorKit.Graphics2D.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Text.Json" />
    </ItemGroup>
</Project>
