<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Script.LiveCode.Test" />
        <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
        <PackageReference Include="System.CommandLine" Version="2.0.8" />
    </ItemGroup>

    <PropertyGroup>
        <SourceUpdateRoslynPath>$(MSBuildBinPath)\DotnetTools\dotnet-format</SourceUpdateRoslynPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Microsoft.CodeAnalysis">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Workspaces">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.Workspaces.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.CSharp.Workspaces">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.CSharp.Workspaces.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild.Contracts">
            <HintPath>$(SourceUpdateRoslynPath)\Microsoft.CodeAnalysis.Workspaces.MSBuild.Contracts.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="System.Composition.AttributedModel">
            <HintPath>$(SourceUpdateRoslynPath)\System.Composition.AttributedModel.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="System.Composition.Convention">
            <HintPath>$(SourceUpdateRoslynPath)\System.Composition.Convention.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="System.Composition.Hosting">
            <HintPath>$(SourceUpdateRoslynPath)\System.Composition.Hosting.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="System.Composition.Runtime">
            <HintPath>$(SourceUpdateRoslynPath)\System.Composition.Runtime.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="System.Composition.TypedParts">
            <HintPath>$(SourceUpdateRoslynPath)\System.Composition.TypedParts.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.Script.LiveWorkspace\AlvorKit.Script.LiveWorkspace.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.LiveCode\AlvorKit.LiveCode.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Engine.SourceUpdate\AlvorKit.Engine.SourceUpdate.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="$(SourceUpdateRoslynPath)\BuildHost-netcore\**\*">
            <Link>BuildHost-netcore\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="$(SourceUpdateRoslynPath)\BuildHost-net472\**\*">
            <Link>BuildHost-net472\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.CodeAnalysis" />
        <Using Include="Microsoft.CodeAnalysis.CSharp" />
        <Using Include="Microsoft.CodeAnalysis.CSharp.Syntax" />
        <Using Include="Microsoft.CodeAnalysis.Emit" />
        <Using Include="Microsoft.CodeAnalysis.Text" />
        <Using Include="Microsoft.CodeAnalysis.MSBuild" />
        <Using Include="Microsoft.Build.Locator" />
        <Using Include="System.CommandLine" />
        <Using Include="System.CommandLine.Parsing" />
        <Using Include="System.Collections.Immutable" />
        <Using Include="System.IO.Pipes" />
        <Using Include="System.Reflection.Metadata" />
        <Using Include="System.Reflection.Metadata.Ecma335" />
        <Using Include="System.Reflection.PortableExecutable" />
        <Using Include="System.Security.Cryptography" />
        <Using Include="System.Text.Json.Serialization" />
    </ItemGroup>

</Project>
