<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>Windows x64 and Linux x64/Arm64 native CoreCLR ReJIT profiler for AlvorKit interception.</Description>
        <RepositoryUrl>https://github.com/AlvorKit/AlvorKit</RepositoryUrl>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    </PropertyGroup>

</Project>
