<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ServerGarbageCollection>false</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AlvorKit.Mocking\AlvorKit.Mocking.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Dynamic\AlvorKit.Mocking.Dynamic.csproj" />
        <ProjectReference Include="..\..\src\AlvorKit.Mocking.Interception\AlvorKit.Mocking.Interception.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="AlvorKit.Mocking" />
        <Using Include="AlvorKit.Mocking.Dynamic" />
        <Using Include="AlvorKit.Mocking.Interception" />
        <Using Include="AlvorKit.Mocking.Performance.Fixture" />
        <Using Include="System.Diagnostics" />
        <Using Include="System.Reflection" />
        <Using Include="System.Runtime" />
        <Using Include="System.Runtime.CompilerServices" />
    </ItemGroup>

</Project>
