namespace AlvorKit.Script.BindgenReview;

/// <summary>Validation and shared helpers for the bindgen review command parser.</summary>
internal static partial class BindgenReviewCommandParser
{
    /// <summary>Validates parsed options against command-specific requirements.</summary>
    internal static void Validate(
        BindgenReviewCommandKind kind,
        IReadOnlyList<string> positionals,
        string? caseName,
        bool keep)
    {
        if (positionals.Count != 1)
            throw new ArgumentException($"{kind.ToString().ToLowerInvariant()} requires exactly one positional argument.");
        if (positionals.Any(string.IsNullOrWhiteSpace))
            throw new ArgumentException("Positional arguments must not be blank.");
        if (caseName is not null && kind != BindgenReviewCommandKind.Start)
            throw new ArgumentException("--case is only valid for start.");
        if (keep && kind != BindgenReviewCommandKind.Finish)
            throw new ArgumentException("--keep is only valid for finish.");
    }

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    /// <param name="result">Parse result to inspect.</param>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
