namespace AlvorKit.Script.AgentLease;

/// <summary>Validation and shared helpers for the advisory lease command parser.</summary>
internal static partial class AgentLeaseCommandParser
{
    /// <summary>Validates parsed options against command-specific requirements.</summary>
    /// <param name="kind">Command kind being parsed.</param>
    /// <param name="task">Optional task description.</param>
    /// <param name="mode">Optional coordination mode.</param>
    /// <param name="paths">Path claims supplied by the caller.</param>
    /// <param name="reason">Optional conflict reason.</param>
    internal static void Validate(AgentLeaseCommandKind kind, string? task, string? mode, IReadOnlyList<string> paths, string? reason)
    {
        if (mode is not null && !AgentLeaseModes.IsKnown(mode))
            throw new ArgumentException($"Unknown lease mode '{mode}'.");
        if (kind is AgentLeaseCommandKind.Start && string.IsNullOrWhiteSpace(task))
            throw new ArgumentException("start requires --task.");
        if (kind is AgentLeaseCommandKind.Start or AgentLeaseCommandKind.Check or AgentLeaseCommandKind.Conflict && paths.Count == 0)
            throw new ArgumentException($"{kind.ToString().ToLowerInvariant()} requires at least one --path.");
        if (kind is AgentLeaseCommandKind.Conflict && string.IsNullOrWhiteSpace(reason))
            throw new ArgumentException("conflict requires --reason.");
        if (kind is AgentLeaseCommandKind.Start or AgentLeaseCommandKind.Touch && paths.Any(string.IsNullOrWhiteSpace))
            throw new ArgumentException("Path claims must not be blank.");
    }

    /// <summary>Throws an argument exception when System.CommandLine found parse errors.</summary>
    /// <param name="result">Parse result to inspect.</param>
    private static void ThrowIfErrors(ParseResult result)
    {
        if (result.Action is System.CommandLine.Help.HelpAction)
            throw new ArgumentException("Help is generated by the command-line app.");
        if (result.Errors.Count > 0)
            throw new ArgumentException(string.Join(" ", result.Errors.Select(error => error.Message)));
    }
}
