<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AlvorKit.Maths\AlvorKit.Maths.csproj" />
        <ProjectReference Include="..\AlvorKit.OpenGL.Layer\AlvorKit.OpenGL.Layer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AlvorKit.Graphics2D.Test" />
    </ItemGroup>

</Project>
