using System.Text;

namespace AlvorKit.Script.Bindgen.OpenGLRegistry.Test;

/// <summary>Tests for generated OpenGL convenience overload source.</summary>
[TestClass]
public sealed class GlExtensionsEmitterTest
{
    /// <summary>Combined overloads infer byte counts and pin generic spans for void pointers.</summary>
    [TestMethod]
    public void Emit_CombinedGenericSpanOverloadInfersByteLength()
    {
        var model = ModelWithCommands([
            new(
                NativeName: "glBufferData",
                ManagedName: "BufferData",
                ReturnType: "void",
                ReturnInteropType: "void",
                Parameters:
                [
                    new("size", "size", "nint", "nint", Len: null, PointerDepth: 0, PointeeType: null, PointeeIsConst: false, PointeeIsChar: false),
                    new("data", "data", "nint", "nint", Len: "size", PointerDepth: 1, PointeeType: null, PointeeIsConst: true, PointeeIsChar: false)
                ],
                Availability: new("1.0", null),
                Documentation: null,
                ReturnsCString: false)
        ]);

        var source = new GlExtensionsEmitter(OpenGlRegistryTestConfig.Create()).Emit(model, Header())!;

        StringAssert.Contains(source, "public virtual void BufferData<T>(ReadOnlySpan<T> data) where T : unmanaged");
        StringAssert.Contains(source, "ByteLength<T>(data)");
        StringAssert.Contains(source, "fixed (T* dataPtr = data)");
    }

    /// <summary>Info-log helpers emit allocating string and caller-buffer overloads.</summary>
    [TestMethod]
    public void Emit_InfoLogOverloadsGrowUtf8Buffers()
    {
        var model = ModelWithCommands([
            new(
                NativeName: "glGetShaderInfoLog",
                ManagedName: "GetShaderInfoLog",
                ReturnType: "void",
                ReturnInteropType: "void",
                Parameters:
                [
                    new("shader", "shader", "uint", "uint", Len: null, PointerDepth: 0, PointeeType: null, PointeeIsConst: false, PointeeIsChar: false),
                    new("bufSize", "bufSize", "int", "int", Len: null, PointerDepth: 0, PointeeType: null, PointeeIsConst: false, PointeeIsChar: false),
                    new("length", "length", "nint", "nint", Len: "1", PointerDepth: 1, PointeeType: "int", PointeeIsConst: false, PointeeIsChar: false),
                    new("infoLog", "infoLog", "nint", "nint", Len: "bufSize", PointerDepth: 1, PointeeType: "byte", PointeeIsConst: false, PointeeIsChar: true)
                ],
                Availability: new("1.0", null),
                Documentation: null,
                ReturnsCString: false)
        ]);

        var source = new GlExtensionsEmitter(OpenGlRegistryTestConfig.Create()).Emit(model, Header())!;

        StringAssert.Contains(source, "public virtual string GetShaderInfoLog(uint shader)");
        StringAssert.Contains(source, "return Encoding.UTF8.GetString(buffer[..written]);");
        StringAssert.Contains(source, "public virtual ReadOnlySpan<char> GetShaderInfoLog(uint shader, Span<char> destination)");
    }

    /// <summary>Creates a minimal binding model with the supplied commands.</summary>
    private static GlBindingModel ModelWithCommands(IReadOnlyList<GlCommand> commands) =>
        new([], new("GLenum", "GlEnum", IsFlags: false, Members: []), commands, [], [], [], [], []);

    /// <summary>Creates a generated C# source header for direct extension emitter tests.</summary>
    private static StringBuilder Header() => new StringBuilder().AppendLine("// <auto-generated/>").AppendLine("#nullable enable").AppendLine();
}
