namespace AlvorKit.Script.Bindgen;

/// <summary>Writes generated API, native import, and backend implementation projects.</summary>
public sealed class BindingCodeEmitter(BindgenConfig config, string tag)
{
    private const string AutoGeneratedMarker = "// <auto-generated/>";

    public void Emit(BindingModel model, string repoRoot, string version)
    {
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        RecreateDirectory(apiDirectory);
        RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), EmitApiProject(version));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"), EmitBackendProject(version, apiProjectName));

        foreach (var inlineBuffer in model.InlineBuffers)
            File.WriteAllText(Path.Combine(apiDirectory, inlineBuffer.ManagedName + ".cs"), EmitInlineBuffer(inlineBuffer));
        foreach (var enumType in model.Enums)
            File.WriteAllText(Path.Combine(apiDirectory, enumType.ManagedName + ".cs"), EmitEnum(enumType));
        foreach (var structType in model.Structs)
            File.WriteAllText(Path.Combine(apiDirectory, structType.ManagedName + ".cs"), EmitStruct(structType));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), EmitApiContract(model));
        if (config.SpanExtensions && EmitSpanExtensions(model) is { } spanExtensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), spanExtensions);
        File.WriteAllText(Path.Combine(backendDirectory, config.NativeClass + ".cs"), EmitNativeImports(model));
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), EmitBackend(model));
    }

    /// <summary>The C sizeof helpers for caller-allocated types, compiled into the native library.</summary>
    public string EmitSizeofShim(BindingModel model)
    {
        var output = new StringBuilder()
            .AppendLine(AutoGeneratedMarker)
            .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}).")
            .AppendLine();
        foreach (var nativeType in model.SizeofTypes)
            output.AppendLine($"{config.ShimExport} size_t alvorkit_sizeof_{nativeType}(void) {{ return sizeof({nativeType}); }}");
        return output.ToString();
    }

    private static void RecreateDirectory(string directory)
    {
        if (Directory.Exists(directory))
            Directory.Delete(directory, true);
        Directory.CreateDirectory(directory);
    }

    private string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}). -->";

    private StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine(AutoGeneratedMarker)
        .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {config.NativeLibrary} {tag} ({config.Header}).")
        .AppendLine();

    private static string EmitSharedProps() => """
        <!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen. -->
        <Project>
            <PropertyGroup>
                <TargetFramework>net10.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
                <PackageReadmeFile>README.md</PackageReadmeFile>
                <PackageLicenseExpression>MIT</PackageLicenseExpression>
                <GenerateDocumentationFile>true</GenerateDocumentationFile>
                <!-- Imported upstream docs sometimes name parameters differently than the declaration. -->
                <NoWarn>$(NoWarn);CS1573</NoWarn>
            </PropertyGroup>

            <PropertyGroup>
                <BaseOutputPath>..\..\..\bin\$(MSBuildProjectName)</BaseOutputPath>
                <BaseIntermediateOutputPath>..\..\..\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
                <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
            </PropertyGroup>

            <ItemGroup>
                <Using Include="System.Runtime.CompilerServices" />
                <Using Include="System.Runtime.InteropServices" />
                <None Include="..\..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
            </ItemGroup>
        </Project>

        """;

    private string EmitApiProject(string version) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>{(config.SpanExtensions ? "\n        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>" : "")}
            </PropertyGroup>

        </Project>

        """;

    private string EmitBackendProject(string version, string apiProjectName) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <PackageReference Include="{config.Namespace}.Native" Version="{version}" />
            </ItemGroup>

            <ItemGroup>
                <ProjectReference Include="..\{apiProjectName}\{apiProjectName}.csproj" />
            </ItemGroup>

        </Project>

        """;

    private string EmitEnum(BindingEnum enumType)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>{enumType.Documentation ?? $"Maps {enumType.NativeName}."}</summary>");
        if (enumType.IsFlags)
            output.AppendLine("[Flags]");
        output.AppendLine($"public enum {enumType.ManagedName}{(enumType.UnderlyingType == "int" ? "" : " : " + enumType.UnderlyingType)}");
        output.AppendLine("{");
        foreach (var member in enumType.Members)
        {
            if (member.Documentation is not null)
                output.AppendLine($"    /// <summary>{member.Documentation}</summary>");
            output.AppendLine($"    {member.ManagedName} = {member.Value},");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitStruct(BindingStruct structType)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>{structType.Documentation ?? $"Maps {structType.NativeName}."}</summary>");
        output.AppendLine(structType.IsUnion
            ? "[StructLayout(LayoutKind.Explicit)]"
            : "[StructLayout(LayoutKind.Sequential)]");
        output.AppendLine($"public struct {structType.ManagedName}");
        output.AppendLine("{");
        foreach (var field in structType.Fields)
        {
            if (field.Documentation is not null)
                output.AppendLine($"    /// <summary>{field.Documentation}</summary>");
            output.AppendLine($"    {(structType.IsUnion ? "[FieldOffset(0)] " : "")}public {field.ManagedType} {field.ManagedName};");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitApiContract(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// {config.ApiSummary}");
        output.AppendLine($"/// Use through a backend implementation, such as {config.BackendClass} from {config.Namespace}.Backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}");
        output.AppendLine("{");
        foreach (var constant in model.Constants)
            output.AppendLine(constant.Value is >= int.MinValue and <= int.MaxValue
                ? $"    public const int {constant.ManagedName} = {constant.Value};"
                : $"    public const long {constant.ManagedName} = {constant.Value};");

        var first = model.Constants.Count == 0;
        foreach (var function in model.Functions)
        {
            if (!first)
                output.AppendLine();
            first = false;
            EmitDocs(output, function);
            output.AppendLine($"    public virtual {function.ReturnType} {function.ManagedName}({Signature(function)}) => throw new NotImplementedException();");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// Extension methods on the API class with every span/pointer combination of
    /// the buffer parameters: each detected pointer+length pair (or configured
    /// length-less pointer) can independently become a generic span, pinned for
    /// the duration of the call.
    /// </summary>
    private string? EmitSpanExtensions(BindingModel model)
    {
        var overloads = new StringBuilder();
        foreach (var function in model.Functions)
        {
            var candidates = SpanCandidates(function);
            if (candidates.Count == 0)
                continue;

            var full = (1 << candidates.Count) - 1;
            EmitSpanOverload(overloads, function, candidates, full);
            for (var mask = 1; mask < full; mask++)
                EmitSpanOverload(overloads, function, candidates, mask);
        }
        if (overloads.Length == 0)
            return null;

        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// Span overloads for the <see cref=\"{config.ApiClass}\"/> functions whose pointer+length parameters describe");
        output.AppendLine("/// a buffer consumed during the call: the spans (any unmanaged element) are pinned for the duration of");
        output.AppendLine("/// the call and passed through, in every span/pointer combination.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public static unsafe class {config.ApiClass}Extensions");
        output.AppendLine("{");
        output.Append(overloads);
        output.AppendLine("    // A span holds at most int.MaxValue elements, so the product fits 64-bit nuint for any unmanaged T;");
        output.AppendLine("    // checked() covers 32-bit processes, where a span describing more memory than the address space");
        output.AppendLine("    // would otherwise wrap into a silently wrong length.");
        output.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        output.AppendLine("    private static nuint ByteLength<T>(ReadOnlySpan<T> span) where T : unmanaged =>");
        output.AppendLine("        checked((nuint)span.Length * (nuint)sizeof(T));");
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>The buffer parameters of a function that can become spans: untyped pointers followed by a size_t, plus configured length-less ones.</summary>
    private List<(int Pointer, int? Length)> SpanCandidates(BindingFunction function)
    {
        var candidates = new List<(int Pointer, int? Length)>();
        if (config.SpanSkip.ContainsKey(function.NativeName))
            return candidates;

        var lengthlessParams = config.SpanParams.GetValueOrDefault(function.NativeName, []);
        var parameters = function.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            if (!parameters[i].IsUntypedPointer)
                continue;
            if (i + 1 < parameters.Count && parameters[i + 1].IsSizeT)
                candidates.Add((i, i + 1));
            else if (lengthlessParams.Contains(parameters[i].ManagedName.TrimStart('@')))
                candidates.Add((i, null));
        }
        return candidates;
    }

    private void EmitSpanOverload(StringBuilder output, BindingFunction function, List<(int Pointer, int? Length)> candidates, int mask)
    {
        var spanned = candidates.Where((_, index) => (mask & (1 << index)) != 0).ToList();
        var typeParameterByPointer = spanned.ToDictionary(
            candidate => candidate.Pointer,
            candidate => "T" + TypeParameterName(function.Parameters[candidate.Pointer].ManagedName));
        var pointerByLength = spanned.Where(candidate => candidate.Length is not null)
            .ToDictionary(candidate => candidate.Length!.Value, candidate => candidate.Pointer);

        var instance = config.ApiClass.ToLowerInvariant();
        var signature = new List<string> { $"this {config.ApiClass} {instance}" };
        var arguments = new List<string>();
        foreach (var (parameter, index) in function.Parameters.Select((parameter, index) => (parameter, index)))
        {
            if (typeParameterByPointer.TryGetValue(index, out var typeParameter))
            {
                var spanType = parameter.IsConstPointee ? "ReadOnlySpan" : "Span";
                signature.Add($"{spanType}<{typeParameter}> {parameter.ManagedName}");
                arguments.Add($"(nint){parameter.ManagedName}Ptr");
            }
            else if (pointerByLength.TryGetValue(index, out var pointerIndex))
            {
                var pointerParameter = function.Parameters[pointerIndex];
                arguments.Add($"ByteLength<{typeParameterByPointer[pointerIndex]}>({pointerParameter.ManagedName})");
            }
            else
            {
                var modifier = parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "";
                signature.Add($"{modifier}{parameter.ManagedType} {parameter.ManagedName}");
                arguments.Add($"{modifier}{parameter.ManagedName}");
            }
        }

        var typeParameters = spanned.Select(candidate => typeParameterByPointer[candidate.Pointer]).ToList();
        output.AppendLine($"    /// <inheritdoc cref=\"{config.ApiClass}.{function.ManagedName}\"/>");
        output.Append($"    public static {function.ReturnType} {function.ManagedName}<{string.Join(", ", typeParameters)}>({string.Join(", ", signature)})");
        if (typeParameters.Count == 1)
        {
            output.AppendLine($" where {typeParameters[0]} : unmanaged");
        }
        else
        {
            output.AppendLine();
            foreach (var typeParameter in typeParameters)
                output.AppendLine($"        where {typeParameter} : unmanaged");
        }
        output.AppendLine("    {");
        foreach (var candidate in spanned)
        {
            var parameter = function.Parameters[candidate.Pointer];
            output.AppendLine($"        fixed ({typeParameterByPointer[candidate.Pointer]}* {parameter.ManagedName}Ptr = {parameter.ManagedName})");
        }
        var call = $"{instance}.{function.ManagedName}({string.Join(", ", arguments)})";
        output.AppendLine($"            {(function.ReturnType == "void" ? call : "return " + call)};");
        output.AppendLine("    }");
        output.AppendLine();
    }

    private static string TypeParameterName(string managedParameterName)
    {
        var name = managedParameterName.TrimStart('@');
        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private string EmitNativeImports(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine("[assembly: DisableRuntimeMarshalling]");
        output.AppendLine();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>Raw imports from the {config.NativeLibrary} shared library ({config.Namespace}.Native).</summary>");
        output.AppendLine($"internal static partial class {config.NativeClass}");
        output.AppendLine("{");
        output.AppendLine($"    private const string Lib = \"{config.NativeLibrary}\";");
        foreach (var function in model.Functions)
        {
            output.AppendLine();
            var marshalling = function.Parameters.Any(parameter => parameter.RequiresUtf8StringMarshalling)
                ? ", StringMarshalling = StringMarshalling.Utf8"
                : "";
            output.AppendLine($"    [LibraryImport(Lib, EntryPoint = \"{function.NativeName}\"{marshalling})]");
            if (function.ReturnBoolMarshaller is not null)
                output.AppendLine($"    [return: MarshalAs(UnmanagedType.{function.ReturnBoolMarshaller})]");
            output.AppendLine($"    public static partial {function.ReturnType} {function.ManagedName}({Signature(function, native: true)});");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitBackend(BindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>Implements <see cref=\"{config.ApiClass}\"/> against the {config.NativeLibrary} shared library.</summary>");
        output.AppendLine($"public class {config.BackendClass} : {config.ApiClass}");
        output.AppendLine("{");
        var first = true;
        foreach (var function in model.Functions)
        {
            if (!first)
                output.AppendLine();
            first = false;
            var arguments = string.Join(", ", function.Parameters.Select(Argument));
            output.AppendLine($"    public override {function.ReturnType} {function.ManagedName}({Signature(function)}) => {config.NativeClass}.{function.ManagedName}({arguments});");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitInlineBuffer(InlineBufferDefinition buffer)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>A fixed buffer of {buffer.Count} <see cref=\"{buffer.ElementType}\"/> values.</summary>");
        output.AppendLine($"[InlineArray({buffer.Count})]");
        output.AppendLine($"public struct {buffer.ManagedName}");
        output.AppendLine("{");
        output.AppendLine($"    private {buffer.ElementType} element;");
        output.AppendLine("}");
        return output.ToString();
    }

    private static string Signature(BindingFunction function, bool native = false) =>
        string.Join(", ", function.Parameters.Select(parameter =>
        {
            var marshal = native && parameter.BoolMarshaller is not null
                ? $"[MarshalAs(UnmanagedType.{parameter.BoolMarshaller})] "
                : "";
            var modifier = parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "";
            return $"{marshal}{modifier}{parameter.ManagedType} {parameter.ManagedName}";
        }));

    private static string Argument(BindingParameter parameter) =>
        (parameter.Modifier.Length > 0 ? parameter.Modifier + " " : "") + parameter.ManagedName;

    private static void EmitDocs(StringBuilder output, BindingFunction function)
    {
        if (function.Documentation is null)
            return;
        if (function.Documentation.Summary is not null)
            output.AppendLine($"    /// <summary>{function.Documentation.Summary}</summary>");
        foreach (var parameter in function.Parameters)
            if (function.Documentation.Parameters.TryGetValue(parameter.ManagedName.TrimStart('@'), out var text))
                output.AppendLine($"    /// <param name=\"{parameter.ManagedName.TrimStart('@')}\">{text}</param>");
        if (function.Documentation.Returns is not null)
            output.AppendLine($"    /// <returns>{function.Documentation.Returns}</returns>");
        if (function.Documentation.Remarks is not null)
            output.AppendLine($"    /// <remarks>{function.Documentation.Remarks}</remarks>");
    }
}
