namespace AlvorKit.Script.Bindgen;

/// <summary>Writes the generated OpenGL API contract and proc-loading backend projects.</summary>
public sealed class GlCodeEmitter(BindgenConfig config, string tag, string docTag)
{
    public void Emit(GlBindingModel model, string repoRoot, string version)
    {
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        BindingCodeEmitter.RecreateDirectory(apiDirectory);
        BindingCodeEmitter.RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), BindingCodeEmitter.EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), EmitApiProject(version));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"), EmitBackendProject(version, apiProjectName));

        foreach (var group in model.Groups)
            File.WriteAllText(Path.Combine(apiDirectory, group.ManagedName + ".cs"), EmitEnum(group, catchAll: false));
        File.WriteAllText(Path.Combine(apiDirectory, model.AllTokens.ManagedName + ".cs"), EmitEnum(model.AllTokens, catchAll: true));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), EmitApiContract(model));
        if (model.WideConstants.Count > 0)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Constants.cs"), EmitConstants(model));
        if (new GlExtensionsEmitter(config).Emit(model, SourceHeader()) is { } extensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), extensions);
        File.WriteAllText(Path.Combine(apiDirectory, "THIRD-PARTY-NOTICES.txt"), EmitThirdPartyNotices(model));
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), EmitBackend(model));
    }

    private string Origin =>
        $"the OpenGL registry at {tag[..Math.Min(12, tag.Length)]} ({config.GlApi} {config.GlVersion} {config.GlProfile})";

    private string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {Origin}. -->";

    private StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine("// <auto-generated/>")
        .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {Origin}.")
        .AppendLine();

    /// <summary>
    /// "GL 4.2, GL ES 3.1" for items in both APIs, just the desktop part when ES has it not.
    /// A non-numeric desktop value is an extension name and is shown verbatim.
    /// </summary>
    private static string AvailabilityText(GlAvailability availability)
    {
        var desktop = char.IsAsciiDigit(availability.Gl[0]) ? $"GL {availability.Gl}" : availability.Gl;
        return availability.GlEs is null ? desktop : $"{desktop}, GL ES {availability.GlEs}";
    }

    private string EmitApiProject(string version) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <None Include="THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
            </ItemGroup>

        </Project>

        """;

    /// <summary>No .Native package: the platform's GL driver is the native library.</summary>
    private string EmitBackendProject(string version, string apiProjectName) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <ProjectReference Include="..\{apiProjectName}\{apiProjectName}.csproj" />
            </ItemGroup>

        </Project>

        """;

    private string EmitEnum(GlEnumGroup group, bool catchAll)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine(catchAll
            ? $"/// <summary>Every {config.GlApi} {config.GlVersion} {config.GlProfile} token: the fallback type for parameters without a typed group.</summary>"
            : $"/// <summary>Maps the {group.NativeName} group.</summary>");
        if (group.IsFlags)
            output.AppendLine("[Flags]");
        output.AppendLine($"public enum {group.ManagedName} : uint");
        output.AppendLine("{");
        foreach (var member in group.Members)
        {
            output.AppendLine($"    /// <summary>{member.NativeName} ({AvailabilityText(member.Availability)}).</summary>");
            output.AppendLine($"    {member.ManagedName} = 0x{member.Value:X4},");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitApiContract(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// {config.ApiSummary}");
        output.AppendLine($"/// Use through a backend implementation, such as {config.BackendClass} from {config.Namespace}.Backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}");
        output.AppendLine("{");
        var first = true;
        foreach (var command in model.Commands)
        {
            if (!first)
                output.AppendLine();
            first = false;
            EmitCommandDocs(output, command);
            output.AppendLine($"    public virtual {command.ReturnType} {command.ManagedName}({Signature(command)}) => throw new NotImplementedException();");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// The tokens whose values overflow the uint-backed enums (GL_TIMEOUT_IGNORED): genuine 64-bit
    /// sentinel numbers rather than GLenum members, so they are plain constants in their own class.
    /// </summary>
    private string EmitConstants(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine($"/// <summary>OpenGL tokens whose values are too wide for the uint-backed {config.ApiClass} enums.</summary>");
        output.AppendLine($"public static class {config.ApiClass}Constants");
        output.AppendLine("{");
        var first = true;
        foreach (var constant in model.WideConstants)
        {
            if (!first)
                output.AppendLine();
            first = false;
            output.AppendLine($"    /// <summary>{constant.NativeName} ({AvailabilityText(constant.Availability)}).</summary>");
            output.AppendLine($"    public const ulong {constant.ManagedName} = 0x{constant.Value:X};");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    /// <summary>
    /// The GL entry point, its availability and the reference-page purpose as the summary, then a
    /// param tag for each parameter the page documents. Commands without a reference page get just
    /// the entry point and availability.
    /// </summary>
    private void EmitCommandDocs(StringBuilder output, GlCommand command)
    {
        var availability = AvailabilityText(command.Availability);
        if (command.Documentation?.Summary is { } summary)
        {
            var purpose = Capitalize(summary);
            var terminated = purpose.EndsWith('.') || purpose.EndsWith('!') || purpose.EndsWith('?');
            output.AppendLine($"    /// <summary>{command.NativeName} ({availability}) - {purpose}{(terminated ? "" : ".")}</summary>");
        }
        else
        {
            output.AppendLine($"    /// <summary>{command.NativeName} ({availability})</summary>");
        }

        if (command.Documentation is { } documentation)
            foreach (var parameter in command.Parameters)
                if (documentation.Parameters.TryGetValue(parameter.NativeName, out var text))
                    output.AppendLine($"    /// <param name=\"{parameter.NativeName}\">{text}</param>");
    }

    private static string Capitalize(string text) =>
        text.Length > 0 && char.IsAsciiLetterLower(text[0]) ? char.ToUpperInvariant(text[0]) + text[1..] : text;

    /// <summary>
    /// Attribution for the reference-page prose imported into the XML docs, required by the SGI
    /// Free Software License B the OpenGL reference pages are published under.
    /// </summary>
    private string EmitThirdPartyNotices(GlBindingModel model)
    {
        var documented = model.Commands.Count(command => command.Documentation is not null);
        if (documented == 0)
            return $"{config.Namespace} contains no third-party content." + Environment.NewLine;

        var shortDocTag = docTag.Length >= 12 ? docTag[..12] : docTag;
        return $"""
            {config.Namespace} third-party notices
            ===================================

            The XML documentation comments on the {config.ApiClass} commands ({documented} of
            {model.Commands.Count}) are derived from the Khronos OpenGL reference pages (the gl4
            directory of the OpenGL-Refpages repository, commit {shortDocTag}).

            The reference pages are copyright their respective authors and are made available by
            The Khronos Group under the SGI Free Software License B, version 2.0. Portions are
            copyright (c) 1991-2006 Silicon Graphics, Inc. and (c) 2010-2014 The Khronos Group Inc.

            Source and license text:
              https://github.com/KhronosGroup/OpenGL-Refpages
              https://www.khronos.org/registry/OpenGL-Refpages/LICENSES/LicenseRef-FreeB.txt

            """;
    }

    private string EmitBackend(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// Implements <see cref=\"{config.ApiClass}\"/> over function pointers resolved from the current OpenGL context.");
        output.AppendLine("/// Construct it with a proc loader once the context is current.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public unsafe class {config.BackendClass} : {config.ApiClass}");
        output.AppendLine("{");
        foreach (var command in model.Commands)
            output.AppendLine($"    private readonly {DelegateType(command)} {command.NativeName};");

        output.AppendLine();
        output.AppendLine("    /// <summary>");
        output.AppendLine("    /// Resolves every entry point through <paramref name=\"getProcAddress\"/> (such as");
        output.AppendLine("    /// Rgfw.GetProcAddressOpenGL), which must be called with the OpenGL context current.");
        output.AppendLine("    /// Entry points the context does not provide stay unresolved: calling one throws");
        output.AppendLine("    /// <see cref=\"EntryPointNotFoundException\"/> naming the function.");
        output.AppendLine("    /// </summary>");
        output.AppendLine($"    public {config.BackendClass}(Func<string, nint> getProcAddress)");
        output.AppendLine("    {");
        foreach (var command in model.Commands)
            output.AppendLine($"        {command.NativeName} = ({DelegateType(command)})getProcAddress(\"{command.NativeName}\");");
        output.AppendLine("    }");

        foreach (var command in model.Commands)
        {
            output.AppendLine();
            output.AppendLine($"    public override {command.ReturnType} {command.ManagedName}({Signature(command)})");
            output.AppendLine("    {");
            output.AppendLine($"        if ({command.NativeName} is null) throw NotLoaded(\"{command.NativeName}\");");
            output.AppendLine($"        {Call(command)}");
            output.AppendLine("    }");
        }

        output.AppendLine();
        output.AppendLine("    private static EntryPointNotFoundException NotLoaded(string entryPoint) =>");
        output.AppendLine("        new($\"OpenGL entry point not loaded: {entryPoint} (Load not called, or not provided by the current context).\");");
        output.AppendLine("}");
        return output.ToString();
    }

    private static string Signature(GlCommand command) =>
        string.Join(", ", command.Parameters.Select(parameter => $"{parameter.ManagedType} {parameter.ManagedName}"));

    /// <summary>The function pointer type at the interop boundary: enums travel as uint, bool as byte.</summary>
    private static string DelegateType(GlCommand command) =>
        $"delegate* unmanaged<{string.Join(", ", command.Parameters.Select(parameter => parameter.InteropType).Append(command.ReturnInteropType))}>";

    private static string Call(GlCommand command)
    {
        var arguments = command.Parameters.Select(parameter =>
            parameter.ManagedType == parameter.InteropType ? parameter.ManagedName
            : parameter.ManagedType == "bool" ? $"{parameter.ManagedName} ? (byte)1 : (byte)0"
            : $"({parameter.InteropType}){parameter.ManagedName}");
        var call = $"{command.NativeName}({string.Join(", ", arguments)})";

        if (command.ReturnType == "void")
            return $"{call};";
        if (command.ReturnType == command.ReturnInteropType)
            return $"return {call};";
        return command.ReturnType == "bool"
            ? $"return {call} != 0;"
            : $"return ({command.ReturnType}){call};";
    }
}
