namespace AlvorKit.Script.Bindgen;

/// <summary>Writes the generated OpenGL API contract and proc-loading backend projects.</summary>
public sealed class GlCodeEmitter(BindgenConfig config, string tag)
{
    public void Emit(GlBindingModel model, string repoRoot, string version)
    {
        var apiDirectory = Path.Combine(repoRoot, config.ApiProject);
        var backendDirectory = Path.Combine(repoRoot, config.BackendProject);
        BindingCodeEmitter.RecreateDirectory(apiDirectory);
        BindingCodeEmitter.RecreateDirectory(backendDirectory);

        var apiProjectName = Path.GetFileName(config.ApiProject);
        var backendProjectName = Path.GetFileName(config.BackendProject);
        File.WriteAllText(Path.Combine(Path.GetDirectoryName(apiDirectory)!, "Directory.Build.props"), BindingCodeEmitter.EmitSharedProps());
        File.WriteAllText(Path.Combine(apiDirectory, apiProjectName + ".csproj"), EmitApiProject(version));
        File.WriteAllText(Path.Combine(backendDirectory, backendProjectName + ".csproj"), EmitBackendProject(version, apiProjectName));

        foreach (var group in model.Groups)
            File.WriteAllText(Path.Combine(apiDirectory, group.ManagedName + ".cs"), EmitEnum(group, catchAll: false));
        File.WriteAllText(Path.Combine(apiDirectory, model.AllTokens.ManagedName + ".cs"), EmitEnum(model.AllTokens, catchAll: true));

        File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + ".cs"), EmitApiContract(model));
        if (new GlExtensionsEmitter(config).Emit(model, SourceHeader()) is { } extensions)
            File.WriteAllText(Path.Combine(apiDirectory, config.ApiClass + "Extensions.cs"), extensions);
        File.WriteAllText(Path.Combine(backendDirectory, config.BackendClass + ".cs"), EmitBackend(model));
    }

    private string Origin =>
        $"the OpenGL registry at {tag[..Math.Min(12, tag.Length)]} ({config.GlApi} {config.GlVersion} {config.GlProfile})";

    private string XmlBanner() =>
        $"<!-- <auto-generated/> Generated by AlvorKit.Script.Bindgen from {Origin}. -->";

    private StringBuilder SourceHeader() => new StringBuilder()
        .AppendLine("// <auto-generated/>")
        .AppendLine($"// Generated by AlvorKit.Script.Bindgen from {Origin}.")
        .AppendLine();

    /// <summary>"core since 4.2" for feature versions, the extension name otherwise.</summary>
    private static string SinceText(string since) =>
        char.IsAsciiDigit(since[0]) ? $"core since {since}" : since;

    private string EmitApiProject(string version) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

        </Project>

        """;

    /// <summary>No .Native package: the platform's GL driver is the native library.</summary>
    private string EmitBackendProject(string version, string apiProjectName) => $"""
        {XmlBanner()}
        <Project Sdk="Microsoft.NET.Sdk">

            <PropertyGroup>
                <Version>{version}</Version>
                <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
            </PropertyGroup>

            <ItemGroup>
                <ProjectReference Include="..\{apiProjectName}\{apiProjectName}.csproj" />
            </ItemGroup>

        </Project>

        """;

    private string EmitEnum(GlEnumGroup group, bool catchAll)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine(catchAll
            ? $"/// <summary>Every {config.GlApi} {config.GlVersion} {config.GlProfile} token: the fallback type for parameters without a typed group.</summary>"
            : $"/// <summary>Maps the {group.NativeName} group.</summary>");
        if (group.IsFlags)
            output.AppendLine("[Flags]");
        output.AppendLine($"public enum {group.ManagedName} : uint");
        output.AppendLine("{");
        foreach (var member in group.Members)
        {
            output.AppendLine($"    /// <summary>{member.NativeName} ({SinceText(member.Since)}).</summary>");
            output.AppendLine($"    {member.ManagedName} = 0x{member.Value:X4},");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitApiContract(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// {config.ApiSummary}");
        output.AppendLine($"/// Use through a backend implementation, such as {config.BackendClass} from {config.Namespace}.Backend.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public class {config.ApiClass}");
        output.AppendLine("{");
        foreach (var constant in model.WideConstants)
        {
            output.AppendLine($"    /// <summary>{constant.NativeName} ({SinceText(constant.Since)}).</summary>");
            output.AppendLine($"    public const ulong {constant.ManagedName} = 0x{constant.Value:X};");
        }

        var first = model.WideConstants.Count == 0;
        foreach (var command in model.Commands)
        {
            if (!first)
                output.AppendLine();
            first = false;
            output.AppendLine($"    /// <summary>Maps {command.NativeName} ({SinceText(command.Since)}).</summary>");
            output.AppendLine($"    public virtual {command.ReturnType} {command.ManagedName}({Signature(command)}) => throw new NotImplementedException();");
        }
        output.AppendLine("}");
        return output.ToString();
    }

    private string EmitBackend(GlBindingModel model)
    {
        var output = SourceHeader();
        output.AppendLine($"namespace {config.Namespace};");
        output.AppendLine();
        output.AppendLine("/// <summary>");
        output.AppendLine($"/// Implements <see cref=\"{config.ApiClass}\"/> over function pointers resolved from the current OpenGL context.");
        output.AppendLine("/// Call <see cref=\"Load\"/> once after the context is current.");
        output.AppendLine("/// </summary>");
        output.AppendLine($"public unsafe class {config.BackendClass} : {config.ApiClass}");
        output.AppendLine("{");
        foreach (var command in model.Commands)
            output.AppendLine($"    private {DelegateType(command)} {command.NativeName};");

        output.AppendLine();
        output.AppendLine("    /// <summary>");
        output.AppendLine("    /// Resolves every entry point through <paramref name=\"getProcAddress\"/> (such as");
        output.AppendLine("    /// Rgfw.GetProcAddressOpenGL). Entry points the context does not provide stay unresolved:");
        output.AppendLine("    /// calling one throws <see cref=\"EntryPointNotFoundException\"/> naming the function.");
        output.AppendLine("    /// </summary>");
        output.AppendLine("    public void Load(Func<string, nint> getProcAddress)");
        output.AppendLine("    {");
        foreach (var command in model.Commands)
            output.AppendLine($"        {command.NativeName} = ({DelegateType(command)})getProcAddress(\"{command.NativeName}\");");
        output.AppendLine("    }");

        foreach (var command in model.Commands)
        {
            output.AppendLine();
            output.AppendLine($"    public override {command.ReturnType} {command.ManagedName}({Signature(command)})");
            output.AppendLine("    {");
            output.AppendLine($"        if ({command.NativeName} is null) throw NotLoaded(\"{command.NativeName}\");");
            output.AppendLine($"        {Call(command)}");
            output.AppendLine("    }");
        }

        output.AppendLine();
        output.AppendLine("    private static EntryPointNotFoundException NotLoaded(string entryPoint) =>");
        output.AppendLine("        new($\"OpenGL entry point not loaded: {entryPoint} (Load not called, or not provided by the current context).\");");
        output.AppendLine("}");
        return output.ToString();
    }

    private static string Signature(GlCommand command) =>
        string.Join(", ", command.Parameters.Select(parameter => $"{parameter.ManagedType} {parameter.ManagedName}"));

    /// <summary>The function pointer type at the interop boundary: enums travel as uint, bool as byte.</summary>
    private static string DelegateType(GlCommand command) =>
        $"delegate* unmanaged<{string.Join(", ", command.Parameters.Select(parameter => parameter.InteropType).Append(command.ReturnInteropType))}>";

    private static string Call(GlCommand command)
    {
        var arguments = command.Parameters.Select(parameter =>
            parameter.ManagedType == parameter.InteropType ? parameter.ManagedName
            : parameter.ManagedType == "bool" ? $"{parameter.ManagedName} ? (byte)1 : (byte)0"
            : $"({parameter.InteropType}){parameter.ManagedName}");
        var call = $"{command.NativeName}({string.Join(", ", arguments)})";

        if (command.ReturnType == "void")
            return $"{call};";
        if (command.ReturnType == command.ReturnInteropType)
            return $"return {call};";
        return command.ReturnType == "bool"
            ? $"return {call} != 0;"
            : $"return ({command.ReturnType}){call};";
    }
}
